---
title: "Blast hit depuis fasta pour un dossier de fasta"
output: html_document
date: "2024-01-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Base https://rsh249.github.io/bioinformatics/rBlast.html
#Installer Blast+ https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/

```{r library, include=FALSE}
library(DECIPHER)
library(rmarkdown)
library(knitr)
library(phyloseq)
library(dada2)
library(DECIPHER)
library(phangorn)
library(ggplot2)
library(gridExtra)
library(shiny)
library(miniUI)
library(caret)
library(pls)
library(e1071)
library(ggplot2)
library(randomForest)
library(dplyr)
library(ggrepel)
#library(nlme)
library(devtools)
library(reshape2)
library(PMA)
#library(structSSI)
library(ade4)
library(ggnetwork)
library(intergraph)
library(scales)
library(genefilter)
library(impute)
library(phyloseqGraphTest)
library(Biostrings)
library(RSQLite)
library(parallel)
library(ape)
library(taxonomizr)
library('rBLAST')
```

```{r}
#NE LANCER QUE UNE FOIS
libdir='data'
dir.create(libdir)
setwd(libdir)
getNamesAndNodes()
getAccession2taxid(types=c('nucl_gb'))
getAccession2taxid()
system("gunzip *.gz")
read.accession2taxid(list.files('.','accession2taxid'),'accessionTaxa.sql')
print(paste('taxonomizr database built and located at', getwd(), sep=' '))
```

```{r}
#Ne lancer que si la commande suivante ne fonctionne pas en spécifiant le path de blast+
Sys.setenv(PATH = paste(Sys.getenv("PATH"), "C:/Program Files/NCBI/blast-2.15.0+/bin", sep= .Platform$path.sep))
```

```{r}
#prepare for a BLAST query
file_list_VerveurEau <- list.files('/Users/amrozins/Documents/workflow/FASTA/VerveurEau', pattern = "\\.fa$", full.names = TRUE)
file_list_VerveurSedi <- list.files('/Users/amrozins/Documents/workflow/FASTA/VerveurSedi', pattern = "\\.fa$", full.names = TRUE)
file_list_VerveurGD <- list.files('/Users/amrozins/Documents/workflow/FASTA/VerveurGD', pattern = "\\.fa$", full.names = TRUE)

dna_VerveurEau <- readDNAStringSet(file_list_VerveurEau, format='fasta')
dna_VerveurSedi <- readDNAStringSet(file_list_VerveurSedi, format='fasta')
dna_VerveurGD <- readDNAStringSet(file_list_VerveurGD, format='fasta')

bl <- blast(db="/Users/amrozins/Documents/workflow/16S_ribosomal_RNA/16S_ribosomal_RNA")

#Run BLAST query

cl_VerveurEau <- predict(bl, dna_VerveurEau)
cl_VerveurSedi <- predict(bl, dna_VerveurSedi)
cl_VerveurGD <- predict(bl, dna_VerveurGD)

cl_VerveurEau[1:5,]
#to view first 5 hits
summary(cl_VerveurEau)
#shows the top QueryID hits and other summary statistics including percent identity, alignment length and mismatches. 

cl_VerveurSedi[1:5,]
summary(cl_VerveurSedi)

cl_VerveurGD[1:5,]
summary(cl_VerveurGD)
```

```{r}
accid_VerveurEau = as.character(cl_VerveurEau$sseqid_VerveurEau)
accid_VerveurSedi = as.character(cl_VerveurSedi$sseqid_VerveurSedi)
accid_VerveurGD = as.character(cl_VerveurGD$sseqid_VerveurGD)
```

```{r}
taxaNodes<-read.nodes.sql("/Users/amrozins/Documents/workflow/data/nodes.dmp")
taxaNames<-read.names.sql("/Users/amrozins/Documents/workflow/data/names.dmp")
```

```{r}
#takes accession number and gets the taxonomic ID
ids_VerveurEau<-accessionToTaxa(accid_VerveurEau, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
#taxlist displays the taxonomic names from each ID #
taxlist_VerveurEau=getTaxonomy(ids_VerveurEau, taxaNodes, taxaNames)


ids_VerveurSedi<-accessionToTaxa(accid_VerveurSedi, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_VerveurSedi=getTaxonomy(ids_VerveurSedi, taxaNodes, taxaNames)

ids_VerveurGD<-accessionToTaxa(accid_VerveurGD, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_VerveurGD=getTaxonomy(ids_VerveurGD, taxaNodes, taxaNames)
```

```{r}
#Résultats Total VerveurEau
cltax_VerveurEau=cbind(cl_VerveurEau,taxlist_VerveurEau) #bind BLAST hits and taxonomy table
colnames(cltax_VerveurEau)
cltax_VerveurEau
```

```{r}
#Résultats Total VerveurEau
cltax_VerveurSedi=cbind(cl_VerveurSedi,taxlist_VerveurSedi) #bind BLAST hits and taxonomy table
colnames(cltax_VerveurSedi)
cltax_VerveurSedi
```

```{r}
#Résultats Total VerveurEau
cltax_VerveurEau=cbind(cl_VerveurEau,taxlist_VerveurEau) #bind BLAST hits and taxonomy table
colnames(cltax_VerveurEau)
cltax_VerveurEau
```

```{r}
# Tri des résultats par qseqid et pident décroissants
cltax_sorted <- cltax %>% arrange(qseqid, desc(pident))

# Sélection des 5 premiers résultats pour chaque qseqid
cltax5 <- cltax_sorted %>% group_by(qseqid) %>% slice_head(n = 5)
```


```{r}
#Ne prend pour chaque fasta que le résultat avec le max de % identity 
# Group by 'SubjectID' and filter for the row with the highest 'pident' within each group
filtered_cltax <- cltax %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))

# Display the resulting dataframe
filtered_cltax
```

```{r}
#take the taxonomic names that have above a 99.5% identity and place in new data set to manipulate
newdata <- subset(filtered_cltax, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident))

print(newdata)
```

```{r}
newdata2 <- subset(filtered_cltax, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident))

# Emplacement des fichiers .fa
chemin_du_dossier <- "/Users/amrozins/Documents/workflow/FASTA/VerveurEau"

# Fonction pour lire le contenu d'un fichier FASTA avec correspondance partielle
lire_fasta <- function(qseqid, chemin_du_dossier) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers <- list.files(chemin_du_dossier, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers) > 0) {
        seqs <- readDNAStringSet(fichiers[1], format = "fasta")
        return(as.character(seqs))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

# Ajouter une colonne au DataFrame avec le contenu des fichiers FASTA
newdata2$sequence <- sapply(newdata2$qseqid, lire_fasta, chemin_du_dossier)

# Ajouter une colonne avec la longueur des séquences dans contenu_fasta
newdata2$longueur_sequence_pb <- sapply(newdata2$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
newdata2 <- newdata2[, c(names(newdata2)[names(newdata2) != "sequence"], "sequence")]

# Afficher le DataFrame mis à jour
print(newdata2)
```

```{r}
# Sauvegarder newdata au format CSV
write.csv(newdata2, "/Users/alexa/OneDrive/Documents/BioInfo/StageM2/FASTA/newdata2.csv", row.names = FALSE)

```


```{r}
#creates plot of selected dataset comparing family id and percent identity 
ggplot(data=newdata) + aes(x = species, y = pident) +
  geom_point(alpha=0.3, color="tomato", position = "jitter") +
  geom_boxplot(alpha=0) + coord_flip()
```

```{r}
#ggplot for top hits or percent identity of each family
tab <- ggplot(data=filtered_cltax) + 
  geom_boxplot(aes(x=species, y=pident)) + 
  theme(axis.text.x = element_text(angle=90)) +
  ylim(c(95,100)) 

print(tab)
```

```{r}
#Comparing alignment length for each family 
ggplot(data=cltax) + 
  geom_boxplot(aes(x=species, y=length)) + 
  theme(axis.text.x = element_text(angle=90))
```
