---
title: "R Notebook"
output: html_notebook
---
TEST
#Installer Blast+ https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/
#Télécharger database 16s de NCBI https://ftp.ncbi.nlm.nih.gov/blast/db/ (16S_ribosomal_RNA...)
#Hahsler M, Anurag N (2024). rBLAST: R Interface for the Basic Local Alignment Search Tool. R package version 1.0.0, https://github.com/mhahsler/rBLAST.

```{r, eval=FALSE, packages mais il doit en manquer, voir avec les library}
install.packages(c("VennDiagram", "VennCounts"))
install.packages("readxl")
```

```{r library, include=FALSE}
library(readxl)
library(openxlsx)
library(VennDiagram)
library(DECIPHER)
library(openxlsx)
library(rmarkdown)
library(knitr)
library(phyloseq)
library(dada2)
library(DECIPHER)
library(phangorn)
library(ggplot2)
library(gridExtra)
library(shiny)
library(miniUI)
library(caret)
library(pls)
library(e1071)
library(ggplot2)
library(randomForest)
library(dplyr)
library(ggrepel)
#library(nlme)
library(devtools)
library(reshape2)
library(PMA)
#library(structSSI)
library(ade4)
library(ggnetwork)
library(intergraph)
library(scales)
library(genefilter)
library(impute)
library(phyloseqGraphTest)
library(Biostrings)
library(RSQLite)
library(parallel)
library(ape)
library(taxonomizr)
library('rBLAST')
library(reshape2)
library(ggvenn)
library(cowplot)
library(patchwork)
```

```{r, eval=FALSE, créer la data base, prévoire 2-3h et 80go de stockage, NE LANCER qu'une fois}
libdir='data'
dir.create(libdir)
setwd(libdir)
getNamesAndNodes()
getAccession2taxid(types=c('nucl_gb'))
getAccession2taxid()
system("gunzip *.gz")
read.accession2taxid(list.files('.','accession2taxid'),'accessionTaxa.sql')
print(paste('taxonomizr database built and located at', getwd(), sep=' '))
```

```{r, Ne lancer que si la commande suivante ne fonctionne pas en spécifiant le path de blast+}
Sys.setenv(PATH = paste(Sys.getenv("PATH"), "C:/Program Files/NCBI/blast-2.15.0+/bin", sep= .Platform$path.sep))
```

```{r}
#BLAST query
file_list_BarnenezEau <- list.files('/Users/amrozins/Documents/workflow/Sequences/BarnenezEau', pattern = "\\.fa$", full.names = TRUE)
file_list_BarnenezSedi <- list.files('/Users/amrozins/Documents/workflow/Sequences/BarnenezSedi', pattern = "\\.fa$", full.names = TRUE)
file_list_BarnenezGDND <- list.files('/Users/amrozins/Documents/workflow/Sequences/BarnenezGDND', pattern = "\\.fa$", full.names = TRUE)
file_list_BarnenezGDDEP <- list.files('/Users/amrozins/Documents/workflow/Sequences/BarnenezGDDEP', pattern = "\\.fa$", full.names = TRUE)
file_list_VerveurEau <- list.files('/Users/amrozins/Documents/workflow/Sequences/VerveurEau', pattern = "\\.fa$", full.names = TRUE)
file_list_VerveurSedi <- list.files('/Users/amrozins/Documents/workflow/Sequences/VerveurSedi', pattern = "\\.fa$", full.names = TRUE)
file_list_VerveurGDND <- list.files('/Users/amrozins/Documents/workflow/Sequences/VerveurGDND', pattern = "\\.fa$", full.names = TRUE)
file_list_VerveurGDDEP <- list.files('/Users/amrozins/Documents/workflow/Sequences/VerveurGDDEP', pattern = "\\.fa$", full.names = TRUE)

dna_BarnenezEau <- readDNAStringSet(file_list_BarnenezEau, format='fasta')
dna_BarnenezSedi <- readDNAStringSet(file_list_BarnenezSedi, format='fasta')
dna_BarnenezGDND <- readDNAStringSet(file_list_BarnenezGDND, format='fasta')
dna_BarnenezGDDEP <- readDNAStringSet(file_list_BarnenezGDDEP, format='fasta')
dna_VerveurEau <- readDNAStringSet(file_list_VerveurEau, format='fasta')
dna_VerveurSedi <- readDNAStringSet(file_list_VerveurSedi, format='fasta')
dna_VerveurGDND <- readDNAStringSet(file_list_VerveurGDND, format='fasta')
dna_VerveurGDDEP <- readDNAStringSet(file_list_VerveurGDDEP, format='fasta')

bl <- blast(db="/Users/amrozins/Documents/workflow/16S_ribosomal_RNA/16S_ribosomal_RNA", type = "blastn")

#Run BLAST query
fmt <- "qseqid saccver pident length evalue qcovs"
#When not provided, the default value is: 'qaccver saccver pident length mismatch gapopen qstart qend sstart send evalue bitscore'
#voir rBLAST help
cl_BarnenezEau <- predict(bl, dna_BarnenezEau, custom_format = fmt)
cl_BarnenezSedi <- predict(bl, dna_BarnenezSedi, custom_format = fmt)
cl_BarnenezGDND <- predict(bl, dna_BarnenezGDND, custom_format = fmt)
cl_BarnenezGDDEP <- predict(bl, dna_BarnenezGDDEP, custom_format = fmt)
cl_VerveurEau <- predict(bl, dna_VerveurEau, custom_format = fmt)
cl_VerveurSedi <- predict(bl, dna_VerveurSedi, custom_format = fmt)
cl_VerveurGDND <- predict(bl, dna_VerveurGDND, custom_format = fmt)
cl_VerveurGDDEP <- predict(bl, dna_VerveurGDDEP, custom_format = fmt)

cl_BarnenezEau[1:5,]
#affiche les premiers 5 hits
summary(cl_BarnenezEau)
cl_BarnenezSedi[1:5,]
summary(cl_BarnenezSedi)
cl_BarnenezGDND[1:5,]
summary(cl_BarnenezGDND)
cl_BarnenezGDDEP[1:5,]
summary(cl_BarnenezGDDEP)
cl_VerveurEau[1:5,]
summary(cl_VerveurEau)
cl_VerveurSedi[1:5,]
summary(cl_VerveurSedi)
cl_VerveurGDND[1:5,]
summary(cl_VerveurGDND)
cl_VerveurGDDEP[1:5,]
summary(cl_VerveurGDDEP)
```

```{r}
accid_BarnenezEau = as.character(cl_BarnenezEau$saccver)
accid_BarnenezSedi = as.character(cl_BarnenezSedi$saccver)
accid_BarnenezGDND = as.character(cl_BarnenezGDND$saccver)
accid_BarnenezGDDEP = as.character(cl_BarnenezGDDEP$saccver)
accid_VerveurEau = as.character(cl_VerveurEau$saccver)
accid_VerveurSedi = as.character(cl_VerveurSedi$saccver)
accid_VerveurGDND = as.character(cl_VerveurGDND$saccver)
accid_VerveurGDDEP = as.character(cl_VerveurGDDEP$saccver)
```

```{r}
taxaNodes<-read.nodes.sql("/Users/amrozins/Documents/workflow/data/nodes.dmp")
taxaNames<-read.names.sql("/Users/amrozins/Documents/workflow/data/names.dmp")
```

```{r}
#takes accession number and gets the taxonomic ID
ids_BarnenezEau<-accessionToTaxa(accid_BarnenezEau, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
#taxlist displays the taxonomic names from each ID #
taxlist_BarnenezEau=getTaxonomy(ids_BarnenezEau, taxaNodes, taxaNames)
ids_BarnenezSedi<-accessionToTaxa(accid_BarnenezSedi, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_BarnenezSedi=getTaxonomy(ids_BarnenezSedi, taxaNodes, taxaNames)
ids_BarnenezGDND<-accessionToTaxa(accid_BarnenezGDND, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_BarnenezGDND=getTaxonomy(ids_BarnenezGDND, taxaNodes, taxaNames)
ids_BarnenezGDDEP<-accessionToTaxa(accid_BarnenezGDDEP, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_BarnenezGDDEP=getTaxonomy(ids_BarnenezGDDEP, taxaNodes, taxaNames)
ids_VerveurEau<-accessionToTaxa(accid_VerveurEau, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_VerveurEau=getTaxonomy(ids_VerveurEau, taxaNodes, taxaNames)
ids_VerveurSedi<-accessionToTaxa(accid_VerveurSedi, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_VerveurSedi=getTaxonomy(ids_VerveurSedi, taxaNodes, taxaNames)
ids_VerveurGDND<-accessionToTaxa(accid_VerveurGDND, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_VerveurGDND=getTaxonomy(ids_VerveurGDND, taxaNodes, taxaNames)
ids_VerveurGDDEP<-accessionToTaxa(accid_VerveurGDDEP, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_VerveurGDDEP=getTaxonomy(ids_VerveurGDDEP, taxaNodes, taxaNames)
```

```{r, Résultats Totaux BarnenezEau}
cltax_BarnenezEau=cbind(cl_BarnenezEau,taxlist_BarnenezEau) #bind BLAST hits and taxonomy table
colnames(cltax_BarnenezEau)
cltax_BarnenezEau
```

```{r, Résultats Totaux BarnenezSedi}
cltax_BarnenezSedi=cbind(cl_BarnenezSedi,taxlist_BarnenezSedi)
colnames(cltax_BarnenezSedi)
cltax_BarnenezSedi
```

```{r, Résultats Totaux BarnenezGDND}
cltax_BarnenezGDND=cbind(cl_BarnenezGDND,taxlist_BarnenezGDND) 
colnames(cltax_BarnenezGDND)
cltax_BarnenezGDND
```

```{r, Résultats Totaux BarnenezGDDEP}
cltax_BarnenezGDDEP=cbind(cl_BarnenezGDDEP,taxlist_BarnenezGDDEP)
colnames(cltax_BarnenezGDDEP)
cltax_BarnenezGDDEP
```

```{r, Résultats Totaux VerveurEau}
cltax_VerveurEau=cbind(cl_VerveurEau,taxlist_VerveurEau) #bind BLAST hits and taxonomy table
colnames(cltax_VerveurEau)
cltax_VerveurEau
```

```{r, Résultats Totaux VerveurSedi}
cltax_VerveurSedi=cbind(cl_VerveurSedi,taxlist_VerveurSedi) #bind BLAST hits and taxonomy table
colnames(cltax_VerveurSedi)
cltax_VerveurSedi
```

```{r, Résultats Totaux VerveurGDND}
cltax_VerveurGDND=cbind(cl_VerveurGDND,taxlist_VerveurGDND) 
colnames(cltax_VerveurGDND)
cltax_VerveurGDND
```

```{r, Résultats Totaux VerveurGDDEP}
cltax_VerveurGDDEP=cbind(cl_VerveurGDDEP,taxlist_VerveurGDDEP)
colnames(cltax_VerveurGDDEP)
cltax_VerveurGDDEP
```

```{r, top 5}
# Tri des résultats par qseqid et pident décroissants
cltax_sorted_BarnenezEau <- cltax_BarnenezEau %>% arrange(qseqid, desc(pident))

# Sélection des 5 premiers résultats pour chaque qseqid
cltax5_BarnenezEau <- cltax_sorted_BarnenezEau %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_BarnenezEau)
```

```{r, top 5}
cltax_sorted_BarnenezSedi <- cltax_BarnenezSedi %>% arrange(qseqid, desc(pident))
cltax5_BarnenezSedi <- cltax_sorted_BarnenezSedi %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_BarnenezSedi)
```

```{r, top 5}
cltax_sorted_BarnenezGDND <- cltax_BarnenezGDND %>% arrange(qseqid, desc(pident))
cltax5_BarnenezGDND <- cltax_sorted_BarnenezGDND %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_BarnenezGDND)
```

```{r, top 5}
cltax_sorted_BarnenezGDDEP <- cltax_BarnenezGDDEP %>% arrange(qseqid, desc(pident))
cltax5_BarnenezGDDEP <- cltax_sorted_BarnenezGDDEP %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_BarnenezGDDEP)
```

```{r, top 5}
# Tri des résultats par qseqid et pident décroissants
cltax_sorted_VerveurEau <- cltax_VerveurEau %>% arrange(qseqid, desc(pident))

# Sélection des 5 premiers résultats pour chaque qseqid
cltax5_VerveurEau <- cltax_sorted_VerveurEau %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_VerveurEau)
```

```{r, top 5}
cltax_sorted_VerveurSedi <- cltax_VerveurSedi %>% arrange(qseqid, desc(pident))
cltax5_VerveurSedi <- cltax_sorted_VerveurSedi %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_VerveurSedi)
```

```{r, top 5}
cltax_sorted_VerveurGDND <- cltax_VerveurGDND %>% arrange(qseqid, desc(pident))
cltax5_VerveurGDND <- cltax_sorted_VerveurGDND %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_VerveurGDND)
```

```{r, top 5}
cltax_sorted_VerveurGDDEP <- cltax_VerveurGDDEP %>% arrange(qseqid, desc(pident))
cltax5_VerveurGDDEP <- cltax_sorted_VerveurGDDEP %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_VerveurGDDEP)
```

```{r, max % identité}
#Ne prend pour chaque fasta que le résultat avec le max de % identity (pident)
filtered_cltax_BarnenezEau <- cltax_sorted_BarnenezEau %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))

filtered_cltax_BarnenezEau
```

```{r, max % identité}
filtered_cltax_BarnenezSedi <- cltax_sorted_BarnenezSedi %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_BarnenezSedi
```

```{r, max % identité}
filtered_cltax_BarnenezGDND <- cltax_sorted_BarnenezGDND %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_BarnenezGDND
```

```{r, max % identité}
filtered_cltax_BarnenezGDDEP <- cltax_sorted_BarnenezGDDEP %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_BarnenezGDDEP
```

```{r, max % identité}
#Ne prend pour chaque fasta que le résultat avec le max de % identity (pident)
filtered_cltax_VerveurEau <- cltax_sorted_VerveurEau %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))

filtered_cltax_VerveurEau
```

```{r, max % identité}
filtered_cltax_VerveurSedi <- cltax_sorted_VerveurSedi %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_VerveurSedi
```

```{r, max % identité}
filtered_cltax_VerveurGDND <- cltax_sorted_VerveurGDND %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_VerveurGDND
```

```{r, max % identité}
filtered_cltax_VerveurGDDEP <- cltax_sorted_VerveurGDDEP %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_VerveurGDDEP
```

#Pour sortir les TabRésultats

```{r}
#Résultats de taxo et ajoutes la longueur de la séquence et la séquence
data_BarnenezEau <- subset(filtered_cltax_BarnenezEau, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident, evalue, qcovs, length))

# Emplacement des fichiers .fasta
chemin_du_dossier_BarnenezEau <- "/Users/amrozins/Documents/workflow/Sequences/BarnenezEau"

# Fonction pour lire le contenu d'un fichier FASTA avec correspondance partielle
lire_fasta_BarnenezEau <- function(qseqid, chemin_du_dossier_BarnenezEau) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_BarnenezEau <- list.files(chemin_du_dossier_BarnenezEau, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_BarnenezEau) > 0) {
        seqs_BarnenezEau <- readDNAStringSet(fichiers_BarnenezEau[1], format = "fasta")
        return(as.character(seqs_BarnenezEau))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

# Ajouter une colonne au DataFrame avec le contenu des fichiers FASTA
data_BarnenezEau$sequence <- sapply(data_BarnenezEau$qseqid, lire_fasta_BarnenezEau, chemin_du_dossier_BarnenezEau)

# Ajouter une colonne avec la longueur des séquences dans contenu_fasta
data_BarnenezEau$longueur_sequence_pb <- sapply(data_BarnenezEau$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_BarnenezEau <- data_BarnenezEau[, c(names(data_BarnenezEau)[names(data_BarnenezEau) != "sequence"], "sequence")]

# Afficher le DataFrame mis à jour
print(data_BarnenezEau)
```


```{r}
data_BarnenezSedi <- subset(filtered_cltax_BarnenezSedi, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident, evalue, qcovs, length))
chemin_du_dossier_BarnenezSedi <- "/Users/amrozins/Documents/workflow/Sequences/BarnenezSedi"

lire_fasta_BarnenezSedi <- function(qseqid, chemin_du_dossier_BarnenezSedi) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_BarnenezSedi <- list.files(chemin_du_dossier_BarnenezSedi, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_BarnenezSedi) > 0) {
        seqs_BarnenezSedi <- readDNAStringSet(fichiers_BarnenezSedi[1], format = "fasta")
        return(as.character(seqs_BarnenezSedi))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_BarnenezSedi$sequence <- sapply(data_BarnenezSedi$qseqid, lire_fasta_BarnenezSedi, chemin_du_dossier_BarnenezSedi)
data_BarnenezSedi$longueur_sequence_pb <- sapply(data_BarnenezSedi$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_BarnenezSedi <- data_BarnenezSedi[, c(names(data_BarnenezSedi)[names(data_BarnenezSedi) != "sequence"], "sequence")]
print(data_BarnenezSedi)
```


```{r}
data_BarnenezGDND <- subset(filtered_cltax_BarnenezGDND, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident, evalue, qcovs, length))
chemin_du_dossier_BarnenezGDND <- "/Users/amrozins/Documents/workflow/Sequences/BarnenezGDND"

lire_fasta_BarnenezGDND <- function(qseqid, chemin_du_dossier_BarnenezGDND) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_BarnenezGDND <- list.files(chemin_du_dossier_BarnenezGDND, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_BarnenezGDND) > 0) {
        seqs_BarnenezGDND <- readDNAStringSet(fichiers_BarnenezGDND[1], format = "fasta")
        return(as.character(seqs_BarnenezGDND))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_BarnenezGDND$sequence <- sapply(data_BarnenezGDND$qseqid, lire_fasta_BarnenezGDND, chemin_du_dossier_BarnenezGDND)
data_BarnenezGDND$longueur_sequence_pb <- sapply(data_BarnenezGDND$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_BarnenezGDND <- data_BarnenezGDND[, c(names(data_BarnenezGDND)[names(data_BarnenezGDND) != "sequence"], "sequence")]
print(data_BarnenezGDND)
```

```{r}
data_BarnenezGDDEP <- subset(filtered_cltax_BarnenezGDDEP, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident, evalue, qcovs, length))
chemin_du_dossier_BarnenezGDDEP <- "/Users/amrozins/Documents/workflow/Sequences/BarnenezGDDEP"

lire_fasta_BarnenezGDDEP <- function(qseqid, chemin_du_dossier_BarnenezGDDEP) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_BarnenezGDDEP <- list.files(chemin_du_dossier_BarnenezGDDEP, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_BarnenezGDDEP) > 0) {
        seqs_BarnenezGDDEP <- readDNAStringSet(fichiers_BarnenezGDDEP[1], format = "fasta")
        return(as.character(seqs_BarnenezGDDEP))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_BarnenezGDDEP$sequence <- sapply(data_BarnenezGDDEP$qseqid, lire_fasta_BarnenezGDDEP, chemin_du_dossier_BarnenezGDDEP)
data_BarnenezGDDEP$longueur_sequence_pb <- sapply(data_BarnenezGDDEP$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_BarnenezGDDEP <- data_BarnenezGDDEP[, c(names(data_BarnenezGDDEP)[names(data_BarnenezGDDEP) != "sequence"], "sequence")]
print(data_BarnenezGDDEP)
```

```{r}
#Résultats de taxo et ajoutes la longueur de la séquence et la séquence
data_VerveurEau <- subset(filtered_cltax_VerveurEau, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident, evalue, qcovs, length))

# Emplacement des fichiers .fasta
chemin_du_dossier_VerveurEau <- "/Users/amrozins/Documents/workflow/Sequences/VerveurEau"

# Fonction pour lire le contenu d'un fichier FASTA avec correspondance partielle
lire_fasta_VerveurEau <- function(qseqid, chemin_du_dossier_VerveurEau) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_VerveurEau <- list.files(chemin_du_dossier_VerveurEau, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_VerveurEau) > 0) {
        seqs_VerveurEau <- readDNAStringSet(fichiers_VerveurEau[1], format = "fasta")
        return(as.character(seqs_VerveurEau))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

# Ajouter une colonne au DataFrame avec le contenu des fichiers FASTA
data_VerveurEau$sequence <- sapply(data_VerveurEau$qseqid, lire_fasta_VerveurEau, chemin_du_dossier_VerveurEau)

# Ajouter une colonne avec la longueur des séquences dans contenu_fasta
data_VerveurEau$longueur_sequence_pb <- sapply(data_VerveurEau$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_VerveurEau <- data_VerveurEau[, c(names(data_VerveurEau)[names(data_VerveurEau) != "sequence"], "sequence")]

# Afficher le DataFrame mis à jour
print(data_VerveurEau)
```




```{r}
data_VerveurSedi <- subset(filtered_cltax_VerveurSedi, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident, evalue, qcovs, length))
chemin_du_dossier_VerveurSedi <- "/Users/amrozins/Documents/workflow/Sequences/VerveurSedi"

lire_fasta_VerveurSedi <- function(qseqid, chemin_du_dossier_VerveurSedi) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_VerveurSedi <- list.files(chemin_du_dossier_VerveurSedi, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_VerveurSedi) > 0) {
        seqs_VerveurSedi <- readDNAStringSet(fichiers_VerveurSedi[1], format = "fasta")
        return(as.character(seqs_VerveurSedi))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_VerveurSedi$sequence <- sapply(data_VerveurSedi$qseqid, lire_fasta_VerveurSedi, chemin_du_dossier_VerveurSedi)
data_VerveurSedi$longueur_sequence_pb <- sapply(data_VerveurSedi$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_VerveurSedi <- data_VerveurSedi[, c(names(data_VerveurSedi)[names(data_VerveurSedi) != "sequence"], "sequence")]
print(data_VerveurSedi)
```

```{r}
data_VerveurGDND <- subset(filtered_cltax_VerveurGDND, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident, evalue, qcovs, length))
chemin_du_dossier_VerveurGDND <- "/Users/amrozins/Documents/workflow/Sequences/VerveurGDND"

lire_fasta_VerveurGDND <- function(qseqid, chemin_du_dossier_VerveurGDND) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_VerveurGDND <- list.files(chemin_du_dossier_VerveurGDND, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_VerveurGDND) > 0) {
        seqs_VerveurGDND <- readDNAStringSet(fichiers_VerveurGDND[1], format = "fasta")
        return(as.character(seqs_VerveurGDND))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_VerveurGDND$sequence <- sapply(data_VerveurGDND$qseqid, lire_fasta_VerveurGDND, chemin_du_dossier_VerveurGDND)
data_VerveurGDND$longueur_sequence_pb <- sapply(data_VerveurGDND$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_VerveurGDND <- data_VerveurGDND[, c(names(data_VerveurGDND)[names(data_VerveurGDND) != "sequence"], "sequence")]
print(data_VerveurGDND)
```

```{r}
data_VerveurGDDEP <- subset(filtered_cltax_VerveurGDDEP, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident, evalue, qcovs, length))
chemin_du_dossier_VerveurGDDEP <- "/Users/amrozins/Documents/workflow/Sequences/VerveurGDDEP"

lire_fasta_VerveurGDDEP <- function(qseqid, chemin_du_dossier_VerveurGDDEP) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_VerveurGDDEP <- list.files(chemin_du_dossier_VerveurGDDEP, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_VerveurGDDEP) > 0) {
        seqs_VerveurGDDEP <- readDNAStringSet(fichiers_VerveurGDDEP[1], format = "fasta")
        return(as.character(seqs_VerveurGDDEP))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_VerveurGDDEP$sequence <- sapply(data_VerveurGDDEP$qseqid, lire_fasta_VerveurGDDEP, chemin_du_dossier_VerveurGDDEP)
data_VerveurGDDEP$longueur_sequence_pb <- sapply(data_VerveurGDDEP$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_VerveurGDDEP <- data_VerveurGDDEP[, c(names(data_VerveurGDDEP)[names(data_VerveurGDDEP) != "sequence"], "sequence")]
print(data_VerveurGDDEP)
```



```{r, stats sur les sequences}
# Calculer les moyennes pour all_filtered_dataVerveur
mean_length_verveur <- mean(all_filtered_dataVerveur$length, na.rm = TRUE)
mean_qcovs_verveur <- mean(all_filtered_dataVerveur$qcovs, na.rm = TRUE)
mean_pident_verveur <- mean(all_filtered_dataVerveur$pident, na.rm = TRUE)

# Afficher les moyennes pour all_filtered_dataVerveur
cat("Moyennes pour all_filtered_dataVerveur:\n")
cat("length: ", mean_length_verveur, "\n")
cat("qcovs: ", mean_qcovs_verveur, "\n")
cat("pident: ", mean_pident_verveur, "\n\n")

# Calculer les moyennes pour all_filtered_dataBarnenez
mean_length_barnenez <- mean(all_filtered_dataBarnenez$length, na.rm = TRUE)
mean_qcovs_barnenez <- mean(all_filtered_dataBarnenez$qcovs, na.rm = TRUE)
mean_pident_barnenez <- mean(all_filtered_dataBarnenez$pident, na.rm = TRUE)

# Afficher les moyennes pour all_filtered_dataBarnenez
cat("Moyennes pour all_filtered_dataBarnenez:\n")
cat("length: ", mean_length_barnenez, "\n")
cat("qcovs: ", mean_qcovs_barnenez, "\n")
cat("pident: ", mean_pident_barnenez, "\n\n")

# Combiner les deux dataframes
combined_data <- rbind(all_filtered_dataVerveur, all_filtered_dataBarnenez)

# Calculer les moyennes pour le dataframe combiné
mean_length_combined <- mean(combined_data$length, na.rm = TRUE)
mean_qcovs_combined <- mean(combined_data$qcovs, na.rm = TRUE)
mean_pident_combined <- mean(combined_data$pident, na.rm = TRUE)

# Afficher les moyennes pour le dataframe combiné

cat("Moyennes pour les deux sites combinés:\n")
cat("Length: ", mean_length_combined, "\n")
cat("Qcovs: ", mean_qcovs_combined, "\n")
cat("Pident: ", mean_pident_combined, "\n")
```

```{r, Sauvegarder data_BarnenezGDND au format CSV}
write.csv(data_BarnenezGDND, "/Users/amrozins/Documents/workflow/Résultats/data_BarnenezGDND.csv", row.names = FALSE)
```

```{r, Sauvegarder data_BarnenezGDDEP au format CSV}
write.csv(data_BarnenezGDDEP, "/Users/amrozins/Documents/workflow/Résultats/data_BarnenezGDDEP.csv", row.names = FALSE)
```

```{r, Sauvegarder data_BarnenezSedi au format CSV}
write.csv(data_BarnenezSedi, "/Users/amrozins/Documents/workflow/Résultats/data_BarnenezSedi.csv", row.names = FALSE)
```

```{r, Sauvegarder data_BarnenezEau au format CSV}
write.csv(data_BarnenezEau, "/Users/amrozins/Documents/workflow/Résultats/data_BarnenezEau.csv", row.names = FALSE)
```

```{r, Sauvegarder data_VerveurGDND au format CSV}
write.csv(data_VerveurGDND, "/Users/amrozins/Documents/workflow/Résultats/data_VerveurGDND.csv", row.names = FALSE)
```

```{r, Sauvegarder data_VerveurGDDEP au format CSV}
write.csv(data_VerveurGDDEP, "/Users/amrozins/Documents/workflow/Résultats/data_VerveurGDDEP.csv", row.names = FALSE)
```

```{r, Sauvegarder data_VerveurSedi au format CSV}
write.csv(data_VerveurSedi, "/Users/amrozins/Documents/workflow/Résultats/data_VerveurSedi.csv", row.names = FALSE)
```

```{r, Sauvegarder data_VerveurEau au format CSV}
write.csv(data_VerveurEau, "/Users/amrozins/Documents/workflow/Résultats/data_VerveurEau.csv", row.names = FALSE)
```

```{r, Combine les .csv}
# Chemin du fichier Excel de sortie
output_excel_path <- "/Users/amrozins/Documents/workflow/Résultats/combined_dataBarnenez.xlsx"

# Écrire les données dans un fichier Excel avec plusieurs feuilles
write.xlsx(list(data_BarnenezGDND = data_BarnenezGDND, 
                data_BarnenezGDDEP = data_BarnenezGDDEP,
                data_BarnenezSedi = data_BarnenezSedi, 
                data_BarnenezEau = data_BarnenezEau),
           file = output_excel_path)

```

```{r, Combine les .csv}
# Chemin du fichier Excel de sortie
output_excel_path <- "/Users/amrozins/Documents/workflow/Résultats/combined_dataVerveur.xlsx"

# Écrire les données dans un fichier Excel avec plusieurs feuilles
write.xlsx(list(data_VerveurGDND = data_VerveurGDND, 
                data_VerveurGDDEP = data_VerveurGDDEP,
                data_VerveurSedi = data_VerveurSedi, 
                data_VerveurEau = data_VerveurEau),
           file = output_excel_path)
```

#Représentations Graphique

```{r, Représentation graphique des genres les plus retrouvés pour Barnenez Eau / Sédiments / GD}
# Filtrer pour ne conserver que le résultat avec le plus grand pident par fichier .fa
filtered_data_BarnenezEau <- data_BarnenezEau[order(-data_BarnenezEau$pident), ]
filtered_data_BarnenezEau <- filtered_data_BarnenezEau[!duplicated(filtered_data_BarnenezEau$qseqid), ]

filtered_data_BarnenezSedi <- data_BarnenezSedi[order(-data_BarnenezSedi$pident), ]
filtered_data_BarnenezSedi <- filtered_data_BarnenezSedi[!duplicated(filtered_data_BarnenezSedi$qseqid), ]

filtered_data_BarnenezGDND <- data_BarnenezGDND[order(-data_BarnenezGDND$pident), ]
filtered_data_BarnenezGDND <- filtered_data_BarnenezGDND[!duplicated(filtered_data_BarnenezGDND$qseqid), ]

filtered_data_BarnenezGDDEP <- data_BarnenezGDDEP[order(-data_BarnenezGDDEP$pident), ]
filtered_data_BarnenezGDDEP <- filtered_data_BarnenezGDDEP[!duplicated(filtered_data_BarnenezGDDEP$qseqid), ]

# Combinez les données filtrées en une seule dataframe
all_filtered_dataBarnenez <- rbind(filtered_data_BarnenezEau, filtered_data_BarnenezSedi, filtered_data_BarnenezGDND, filtered_data_BarnenezGDDEP)

# Tableau de comptage des genres
class_countsBarnenez <- table(all_filtered_dataBarnenez$genus)

# Sélectionnez les 10 genres les plus retrouvés
top_genresBarnenez <- head(sort(class_countsBarnenez, decreasing = TRUE), 10)

# Créez le graphique à barres
bar_plotBarnenez <- ggplot(data.frame(Genus = names(top_genresBarnenez), Count = as.numeric(top_genresBarnenez)), 
                   aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#59C9A5") +
  labs(title = "Top 10 genres les plus retrouvés pour Barnenez : Eau / Sédiments / GD (DEP et ND)", x = "genres", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(all_filtered_dataBarnenez)), hjust = 1, vjust = 0)

print(bar_plotBarnenez)
```

```{r}
# Tableau de comptage des genres
genres_countsBarnenez <- table(all_filtered_dataBarnenez$genus)

# Compter le nombre total de genres
total_genres <- length(unique(all_filtered_dataBarnenez$genus))

# Créez le graphique à barres
bar_plotBarnenezTot <- ggplot(data.frame(Genus = names(genres_countsBarnenez), Count = as.numeric(genres_countsBarnenez)), 
                   aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#145C9E") +
  geom_text(aes(label = Count), vjust = -0.5, color = "black", size = 3.5) +  # Ajouter les valeurs au-dessus de chaque barre
  labs(title = "genres retrouvés pour Barnenez : Eau / Sédiments / GD (DEP et ND)", x = "genres", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = 30, y = 12, label = paste("Total de séquences :", nrow(all_filtered_dataBarnenez)), hjust = 1, vjust = 1) +
  annotate("text", x = 30, y = Inf, label = paste("Nombre total de genres :", total_genres), hjust = 1, vjust = 0.95) # Ajouter le nombre total de genres

print(bar_plotBarnenezTot)
```


```{r, Représentation graphique des genres les plus retrouvés pour Verveur Eau / Sédiments / GD}
# Filtrer pour ne conserver que le résultat avec le plus grand pident par fichier .fa
filtered_data_VerveurEau <- data_VerveurEau[order(-data_VerveurEau$pident), ]
filtered_data_VerveurEau <- filtered_data_VerveurEau[!duplicated(filtered_data_VerveurEau$qseqid), ]

filtered_data_VerveurSedi <- data_VerveurSedi[order(-data_VerveurSedi$pident), ]
filtered_data_VerveurSedi <- filtered_data_VerveurSedi[!duplicated(filtered_data_VerveurSedi$qseqid), ]

filtered_data_VerveurGDND <- data_VerveurGDND[order(-data_VerveurGDND$pident), ]
filtered_data_VerveurGDND <- filtered_data_VerveurGDND[!duplicated(filtered_data_VerveurGDND$qseqid), ]

filtered_data_VerveurGDDEP <- data_VerveurGDDEP[order(-data_VerveurGDDEP$pident), ]
filtered_data_VerveurGDDEP <- filtered_data_VerveurGDDEP[!duplicated(filtered_data_VerveurGDDEP$qseqid), ]

# Combinez les données filtrées en une seule dataframe
all_filtered_dataVerveur <- rbind(filtered_data_VerveurEau, filtered_data_VerveurSedi, filtered_data_VerveurGDND, filtered_data_VerveurGDDEP)

# Tableau de comptage des genres
genres_countsVerveur <- table(all_filtered_dataVerveur$genus)

# Sélectionnez les 10 genres les plus retrouvés
top_genresVerveur <- head(sort(genres_countsVerveur, decreasing = TRUE), 10)

# Créez le graphique à barres
bar_plotVerveur <- ggplot(data.frame(Genus = names(top_genresVerveur), Count = as.numeric(top_genresVerveur)), 
                   aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#59C9A5") +
  geom_text(aes(label = Count), vjust = -0.5, color = "black", size = 3.5) +  # Ajouter les valeurs au-dessus de chaque barre
  labs(title = "Top 10 genres les plus retrouvés pour Verveur : Eau / Sédiments / GD (DEP et ND)", x = "genres", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(all_filtered_dataVerveur)), hjust = 1, vjust = 0)

print(bar_plotVerveur)
```

```{r}
# Tableau de comptage des genres
genres_countsVerveur <- table(all_filtered_dataVerveur$genus)

# Compter le nombre total de genres
total_genres <- length(unique(all_filtered_dataVerveur$genus))

# Créez le graphique à barres
bar_plotVerveurTot <- ggplot(data.frame(Genus = names(genres_countsVerveur), Count = as.numeric(genres_countsVerveur)), 
                   aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#59C9A5") +
  geom_text(aes(label = Count), vjust = -0.5, color = "black", size = 3.5) +  # Ajouter les valeurs au-dessus de chaque barre
  labs(title = "genres retrouvés pour Verveur : Eau / Sédiments / GD (DEP et ND)", x = "genres", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = 27, y = 12, label = paste("Total de séquences :", nrow(all_filtered_dataVerveur)), hjust = 1, vjust = 1) +
  annotate("text", x = 27, y = Inf, label = paste("Nombre total de genres :", total_genres), hjust = 1, vjust = 0.95) # Ajouter le nombre total de genres

print(bar_plotVerveurTot)
```

```{r}
# Combinaison des données pour les deux villes
top_genres_combined <- rbind(
  data.frame(Genus = names(top_genresBarnenez), Count = as.numeric(top_genresBarnenez)),
  data.frame(Genus = names(top_genresVerveur), Count = as.numeric(top_genresVerveur))
)

# Agrégation des comptes pour chaque genres
top_genres_combined <- aggregate(Count ~ Genus, data = top_genres_combined, sum)

# Tracé du graphique
bar_plot_combined <- ggplot(top_genres_combined, aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#59C9A5") +
  geom_text(aes(label = Count), vjust = -0.5, color = "black", size = 3.5) +  # Ajouter les valeurs au-dessus de chaque barre
  labs(title = "Top 10 genres les plus retrouvés pour les deux sites combinés", x = "genres", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels = scales::comma, breaks = seq(0, 20, 1), limits = c(0, 20)) +  # Modifier l'échelle des données y
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", sum(top_genres_combined$Count)), hjust = 1, vjust = 0)

print(bar_plot_combined)
```

```{r, Représentation graphique des genres les plus retrouvés pour Verveur et Barnenez Eau / Sédiments / GD}
# Création des dataframes avec une colonne "Count"
top_genresBarnenez_df <- data.frame(Genus = names(top_genresBarnenez), Count = as.numeric(top_genresBarnenez))
top_genresVerveur_df <- data.frame(Genus = names(top_genresVerveur), Count = as.numeric(top_genresVerveur))

# Ajout d'une colonne "Ville" pour chaque dataframe
top_genresBarnenez_df$Ville <- "Barnenez"
top_genresVerveur_df$Ville <- "Verveur"

# Combinaison des deux dataframes
top_genres_combined2 <- rbind(top_genresBarnenez_df, top_genresVerveur_df)

# Tracé du graphique combiné
bar_plot_combined2 <- ggplot(top_genres_combined2, aes(x = reorder(Genus, -Count), y = Count, fill = Ville)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +  # Ajouter les valeurs au-dessus de chaque barre
  labs(title = "Top 10 genres les plus retrouvés pour les deux sites", x = "genres", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = c("Barnenez" = "#145C9E", "Verveur" = "#59C9A5")) +
  scale_y_continuous(labels = scales::comma, breaks = seq(0, 15, 1), limits = c(0, 15)) +  # Modifier l'échelle des données y
  annotate("text", x = Inf, y = 12, label = paste("Total de séquences pour Barnenez:", sum(top_genresBarnenez), "\nTotal de séquences pour Verveur:", sum(top_genresVerveur)), hjust = 1, vjust = -0.1)

print(bar_plot_combined2)
```

```{r, barplot genres}
# Création des dataframes avec une colonne "Count" pour Barnenez
genres_countsBarnenez <- table(all_filtered_dataBarnenez$genus)
total_sequencesBarnenez <- sum(genres_countsBarnenez)
total_genresBarnenez <- length(unique(all_filtered_dataBarnenez$genus))
top_genresBarnenez_df <- data.frame(Genus = names(genres_countsBarnenez), Count = as.numeric(genres_countsBarnenez))
top_genresBarnenez_df$Ville <- "Barnenez"

# Création des dataframes avec une colonne "Count" pour Verveur
genres_countsVerveur <- table(all_filtered_dataVerveur$genus)
total_sequencesVerveur <- sum(genres_countsVerveur)
total_genresVerveur <- length(unique(all_filtered_dataVerveur$genus))
top_genresVerveur_df <- data.frame(Genus = names(genres_countsVerveur), Count = as.numeric(genres_countsVerveur))
top_genresVerveur_df$Ville <- "Verveur"

# Combinaison des deux dataframes
top_genres_combined3 <- rbind(top_genresBarnenez_df, top_genresVerveur_df)

# Nombre total de genres pour les deux sites combinés
total_genres_combined3 <- length(unique(c(all_filtered_dataBarnenez$genus, all_filtered_dataVerveur$genus)))

# Tracé du graphique combiné
bar_plot_combined3 <- ggplot(top_genres_combined3, aes(x = reorder(Genus, -Count), y = Count, fill = Ville)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +  # Ajouter les valeurs au-dessus de chaque barre
  labs(title = "genres les plus retrouvés pour les deux sites", x = "genres", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = c("Barnenez" = "#145C9E", "Verveur" = "#59C9A5")) +
  scale_y_continuous(labels = scales::comma, breaks = seq(0, 15, 1), limits = c(0, 15)) +  # Modifier l'échelle des données y
  annotate("text", x = Inf, y = 9, label = paste("Total de séquences pour Barnenez:", total_sequencesBarnenez, "\nNombre de genres pour Barnenez:", total_genresBarnenez, "\nTotal de séquences pour Verveur:", total_sequencesVerveur, "\nNombre de genres pour Verveur:", total_genresVerveur, "\nNombre total de genres pour les deux sites combinés:", total_genres_combined3), hjust = 1, vjust = -0.1)

print(bar_plot_combined3)
```

```{r}
# Réinitialiser les variables
legend_text <- ""
legend_title <- ""
```

```{r, barplot avec legendes des genreses}
genus <- c("Bacillus", "Microbacterium", "Salinibacterium", "Sanguibacter", "Demequina", 
           "Plantibacter", "Paracoccus", "Pseudovibrio", "Vibrio", "Yoonia", 
           "Pseudorhodobacter", "Pseudosulfitobacter", "Pseudalkalibacillus", 
           "Metabacillus", "Niallia", "Cytobacillus", "Peribacillus", "Carnobacterium", 
           "Hydrogenophaga", "Algoriphagus", "Nonlabens", "Tenacibaculum", 
           "Polaribacter", "Winogradskyella", "Zobellia", "Cellulophaga", 
           "Olleya", "Formosa", "Flavobacterium", "Cobetia", "Pseudoalteromonas", 
           "Shewanella", "Paraglaciecola", "Rahnella", "Pseudocolwellia", 
           "Psychromonas", "Pseudomonas", "Rheinheimera", "Stenotrophomonas", 
           "Aliiglaciecola", "Marinagarivorans", "Cellvibrio", "Motilimonas", "Pedobacter")

class <- c("Bacilli", "Actinomycetes", "Actinomycetes", "Actinomycetes", "Actinomycetes", 
           "Actinomycetes", "Alphaproteobacteria", "Alphaproteobacteria", "Alphaproteobacteria", 
           "Alphaproteobacteria", "Alphaproteobacteria", "Alphaproteobacteria", "Bacilli", 
           "Bacilli", "Bacilli", "Bacilli", "Bacilli", "Bacilli", "Betaproteobacteria", 
           "Cytophagia", "Flavobacteriia", "Flavobacteriia", "Flavobacteriia", "Flavobacteriia", 
           "Flavobacteriia", "Flavobacteriia", "Flavobacteriia", "Flavobacteriia", 
           "Flavobacteriia", "Gammaproteobacteria", "Gammaproteobacteria", "Gammaproteobacteria", 
           "Gammaproteobacteria", "Gammaproteobacteria", "Gammaproteobacteria", "Gammaproteobacteria", 
           "Gammaproteobacteria", "Gammaproteobacteria", "Gammaproteobacteria", "Gammaproteobacteria", 
           "Gammaproteobacteria", "Gammaproteobacteria", "Gammaproteobacteria", "Sphingobacteriia")
bacteria_db <- data.frame(genus, class )

# Définir la correspondance entre les classes et les symboles
class_symbols <- c("Alphaproteobacteria" = "□", 
                   "Betaproteobacteria" = "◇", 
                   "Gammaproteobacteria" = "■", 
                   "Bacilli" = "★", 
                   "Actinomycetes" = "○", 
                   "Cytophagia" = "△", 
                   "Flavobacteriia" = "▲", 
                   "Sphingobacteriia" = "●")

# Ajouter une colonne de symboles au data frame
bacteria_db$symbol <- class_symbols[bacteria_db$class]

# Création des dataframes avec une colonne "Count" pour Barnenez
genres_countsBarnenez <- table(all_filtered_dataBarnenez$genus)
total_sequencesBarnenez <- sum(genres_countsBarnenez)
total_genresBarnenez <- length(unique(all_filtered_dataBarnenez$genus))
top_genresBarnenez_df <- data.frame(Genus = names(genres_countsBarnenez), Count = as.numeric(genres_countsBarnenez))
top_genresBarnenez_df$Ville <- "Barnenez"

# Création des dataframes avec une colonne "Count" pour Verveur
genres_countsVerveur <- table(all_filtered_dataVerveur$genus)
total_sequencesVerveur <- sum(genres_countsVerveur)
total_genresVerveur <- length(unique(all_filtered_dataVerveur$genus))
top_genresVerveur_df <- data.frame(Genus = names(genres_countsVerveur), Count = as.numeric(genres_countsVerveur))
top_genresVerveur_df$Ville <- "Verveur"

# Combinaison des deux dataframes
top_genres_combined3 <- rbind(top_genresBarnenez_df, top_genresVerveur_df)

# Ajouter la colonne "classes" et "symbol" en fusionnant avec le data frame bacteria_db
top_genres_combined3 <- merge(top_genres_combined3, bacteria_db, by.x = "Genus", by.y = "genus", all.x = TRUE)

# Ajouter une colonne pour savoir si le genre a déjà été rencontré et calculer la position des labels
top_genres_combined3 <- top_genres_combined3[order(top_genres_combined3$Genus, top_genres_combined3$Ville), ]
top_genres_combined3$duplicated_genus <- duplicated(top_genres_combined3$Genus) | duplicated(top_genres_combined3$Genus, fromLast = TRUE)

# Ajouter une colonne max_count pour la hauteur maximale de la barre pour chaque genre
top_genres_combined3 <- top_genres_combined3 %>%
  group_by(Genus) %>%
  mutate(max_count = max(Count)) %>%
  ungroup()

# Déterminer la position des labels (centre ou côté)
top_genres_combined3$Label <- ifelse(top_genres_combined3$duplicated_genus, "", top_genres_combined3$symbol)
top_genres_combined3$symbol_y_pos <- ifelse(top_genres_combined3$duplicated_genus, top_genres_combined3$max_count, top_genres_combined3$Count)

# Nombre total de genres pour les deux sites combinés
total_genres_combined3 <- length(unique(c(all_filtered_dataBarnenez$genus, all_filtered_dataVerveur$genus)))

# Tracé du graphique combiné
bar_plot_combinedgenresclasses <- ggplot(top_genres_combined3, aes(x = reorder(Genus, -Count), y = Count, fill = Ville)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(data = subset(top_genres_combined3, duplicated_genus == FALSE), aes(label = Label), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 9) +  # Ajouter les symboles sur le côté
  geom_text(data = subset(top_genres_combined3, duplicated_genus == TRUE), aes(label = symbol, x = Genus, y = symbol_y_pos + 0.5), color = "black", size = 9) +  # Ajouter les symboles au centre au-dessus de la barre la plus haute
  labs(title = "Genres retrouvés pour le site de Verveur et Barnenez", x = "Genres", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12)) +
  scale_fill_manual(values = c("Barnenez" = "#145C9E", "Verveur" = "#59C9A5")) +
  scale_y_continuous(labels = scales::comma, breaks = seq(0, 15, 1), limits = c(0, 15)) +  # Modifier l'échelle des données y
  annotate("text", x = 38, y = 12, label = paste("Total de séquences pour Barnenez:", total_sequencesBarnenez, "\nNombre de séquences pour Barnenez:", total_genresBarnenez, "\nTotal de séquences pour Verveur:", total_sequencesVerveur, "\nNombre de genres pour Verveur:", total_genresVerveur, "\nNombre total de genres pour les deux sites combinés:", total_genres_combined3), hjust = 1, vjust = -0.1, size = 5) +
  theme(legend.position = "right") + 
  guides(fill = guide_legend(title = "Ville"))

legend_text <- paste(names(class_symbols), class_symbols, sep = ": ")
legend_text <- paste(legend_text, collapse = "\n")
legend_title <- "Classes bactérienne :"
# Concaténer les textes avec le titre de la légende
legend_text <- paste(legend_title, "\n", legend_text)
bar_plot_combinedgenresclasses <- bar_plot_combinedgenresclasses + 
  annotate("text", x = Inf, y = Inf, label = legend_text, hjust = 1, vjust = 1, size = 5, color = "black", parse = FALSE)

print(bar_plot_combinedgenresclasses)
```

```{r, heatmap classes}
class_counts_BarnenezGDND <- table(filtered_data_BarnenezGDND$class)
class_counts_BarnenezGDDEP <- table(filtered_data_BarnenezGDDEP$class)
class_counts_BarnenezEau <- table(filtered_data_BarnenezEau$class)
class_counts_BarnenezSedi <- table(filtered_data_BarnenezSedi$class)

class_counts_VerveurGDND <- table(filtered_data_VerveurGDND$class)
class_counts_VerveurGDDEP <- table(filtered_data_VerveurGDDEP$class)
class_counts_VerveurEau <- table(filtered_data_VerveurEau$class)
class_counts_VerveurSedi <- table(filtered_data_VerveurSedi$class)

# Créer les dataframes pour chaque échantillon
heatmap_dataclass_BarnenezGDND <- data.frame(class = names(class_counts_BarnenezGDND), count = as.numeric(class_counts_BarnenezGDND), Condition = "BarnenezGDND")
heatmap_dataclass_BarnenezGDDEP <- data.frame(class = names(class_counts_BarnenezGDDEP), count = as.numeric(class_counts_BarnenezGDDEP), Condition = "BarnenezGDDEP")
heatmap_dataclass_BarnenezEau <- data.frame(class = names(class_counts_BarnenezEau), count = as.numeric(class_counts_BarnenezEau), Condition = "BarnenezEau")
heatmap_dataclass_BarnenezSedi <- data.frame(class = names(class_counts_BarnenezSedi), count = as.numeric(class_counts_BarnenezSedi), Condition = "BarnenezSedi")

heatmap_dataclass_VerveurGDND <- data.frame(class = names(class_counts_VerveurGDND), count = as.numeric(class_counts_VerveurGDND), Condition = "VerveurGDND")
heatmap_dataclass_VerveurGDDEP <- data.frame(class = names(class_counts_VerveurGDDEP), count = as.numeric(class_counts_VerveurGDDEP), Condition = "VerveurGDDEP")
heatmap_dataclass_VerveurEau <- data.frame(class = names(class_counts_VerveurEau), count = as.numeric(class_counts_VerveurEau), Condition = "VerveurEau")
heatmap_dataclass_VerveurSedi <- data.frame(class = names(class_counts_VerveurSedi), count = as.numeric(class_counts_VerveurSedi), Condition = "VerveurSedi")

# Fusionner les dataframes
heatmap_data_class <- rbind(heatmap_dataclass_BarnenezGDND, heatmap_dataclass_BarnenezGDDEP, heatmap_dataclass_BarnenezEau, heatmap_dataclass_BarnenezSedi, heatmap_dataclass_VerveurGDND, heatmap_dataclass_VerveurGDDEP, heatmap_dataclass_VerveurEau, heatmap_dataclass_VerveurSedi)

# Spécifier l'ordre des niveaux du facteur 'Condition'
heatmap_data_class$Condition <- factor(heatmap_data_class$Condition, levels = c("BarnenezGDDEP", "BarnenezGDND", "BarnenezSedi", "BarnenezEau", "VerveurGDDEP", "VerveurGDND", "VerveurSedi", "VerveurEau"))

# Spécifier l'ordre arbitraire des niveaux du facteur 'class'
arbitrary_order <- c("Alphaproteobacteria", "Betaproteobacteria", "Gammaproteobacteria", "Actinomycetes", "Bacilli", "Cytophagia", "Flavobacteriia", "Sphingobacteriia")  # Remplacer par l'ordre désiré
heatmap_data_class$class <- factor(heatmap_data_class$class, levels = arbitrary_order)

separation_position_y <- 4.5  

# heatmap
heatmap_plot_class <- ggplot(heatmap_data_class, aes(x = class, y = Condition, fill = count)) +
  geom_tile() +
  geom_text(aes(label = count), vjust = 0.5, color = "white", size = 6) +  # Augmenter la taille de la police dans les étiquettes
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
  labs(title = "Heatmap de présence des classes bactériens - Verveur et Barnenez", 
       x = "Classes", 
       y = "Compartiments",
       fill = "Nombre de\nsouches :") +  # Changer la légende
  annotate("text", x = 1, y = 8.7, size = 6,label = "n=6 (4%)", color = "black") +
  annotate("text", x = 2, y = 8.7, size = 6,label = "n=1 (<1%)", color = "black") +
  annotate("text", x = 3, y = 8.7, size = 6,label = "n=81 (55%)", color = "black") +
  annotate("text", x = 4, y = 8.7, size = 6,label = "n=9 (6%)", color = "black") +
  annotate("text", x = 5, y = 8.7, size = 6,label = "n=19 (13%)", color = "black") +
  annotate("text", x = 6, y = 8.7, size = 6,label = "n=9 (6%)", color = "black") +
  annotate("text", x = 7, y = 8.7, size = 6,label = "n=19 (13%)", color = "black") +
  annotate("text", x = 8, y = 8.7, size = 6,label = "n=1 (<1%)", color = "black") +
  scale_y_discrete(expand = expand_scale(mult = c(0, 0.13)))+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 25),  # Ajuster la taille de la police des abscisses
        legend.text = element_text(size = 20),  # Modifier la taille de la légende
        axis.text.y = element_text(size = 25),  # Ajuster la taille de la police des ordonnées
        axis.title.x = element_text(size = 20),  # Ajuster la taille de la police du titre des abscisses
        axis.title.y = element_text(size = 20),  # Ajuster la taille de la police du titre des ordonnées
        legend.title = element_text(size = 20),  # Modifier la taille du titre de la légende (nb de séquences)
        plot.title = element_text(hjust = 0.5, size = 16)) +  # Ajuster la taille de la police du titre
  geom_hline(yintercept = separation_position_y, linetype = "longdash", color = "#EF3E36", size = 2)  # Ajouter une ligne horizontale

print(heatmap_plot_class)



```


```{r, heatmap genres}
# Compter le nombre d'occurrences de chaque genus pour chaque échantillon
genus_counts_BarnenezGDND <- table(filtered_data_BarnenezGDND$genus)
genus_counts_BarnenezGDDEP <- table(filtered_data_BarnenezGDDEP$genus)
genus_counts_BarnenezEau <- table(filtered_data_BarnenezEau$genus)
genus_counts_BarnenezSedi <- table(filtered_data_BarnenezSedi$genus)

genus_counts_VerveurGDND <- table(filtered_data_VerveurGDND$genus)
genus_counts_VerveurGDDEP <- table(filtered_data_VerveurGDDEP$genus)
genus_counts_VerveurEau <- table(filtered_data_VerveurEau$genus)
genus_counts_VerveurSedi <- table(filtered_data_VerveurSedi$genus)

# Créer une dataframe pour chaque échantillon
heatmap_datagenus_BarnenezGDND <- data.frame(genus = names(genus_counts_BarnenezGDND), count = as.numeric(genus_counts_BarnenezGDND), Condition = "BarnenezGDND")
heatmap_datagenus_BarnenezGDDEP <- data.frame(genus = names(genus_counts_BarnenezGDDEP), count = as.numeric(genus_counts_BarnenezGDDEP), Condition = "BarnenezGDDEP")
heatmap_datagenus_BarnenezEau <- data.frame(genus = names(genus_counts_BarnenezEau), count = as.numeric(genus_counts_BarnenezEau), Condition = "BarnenezEau")
heatmap_datagenus_BarnenezSedi <- data.frame(genus = names(genus_counts_BarnenezSedi), count = as.numeric(genus_counts_BarnenezSedi), Condition = "BarnenezSedi")

heatmap_datagenus_VerveurGDND <- data.frame(genus = names(genus_counts_VerveurGDND), count = as.numeric(genus_counts_VerveurGDND), Condition = "VerveurGDND")
heatmap_datagenus_VerveurGDDEP <- data.frame(genus = names(genus_counts_VerveurGDDEP), count = as.numeric(genus_counts_VerveurGDDEP), Condition = "VerveurGDDEP")
heatmap_datagenus_VerveurEau <- data.frame(genus = names(genus_counts_VerveurEau), count = as.numeric(genus_counts_VerveurEau), Condition = "VerveurEau")
heatmap_datagenus_VerveurSedi <- data.frame(genus = names(genus_counts_VerveurSedi), count = as.numeric(genus_counts_VerveurSedi), Condition = "VerveurSedi")

# Fusionner les dataframes
heatmap_data_genus <- rbind(heatmap_datagenus_BarnenezGDND, heatmap_datagenus_BarnenezGDDEP, heatmap_datagenus_BarnenezEau, heatmap_datagenus_BarnenezSedi, heatmap_datagenus_VerveurGDND, heatmap_datagenus_VerveurGDDEP,heatmap_datagenus_VerveurEau, heatmap_datagenus_VerveurSedi)

# heatmap
heatmap_plot_genus <- ggplot(heatmap_data_genus, aes(x = genus, y = Condition, fill = count)) +
  geom_tile() +
  geom_text(aes(label = count), vjust = 0.5, color = "white") +  
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
  labs(title = "Heatmap de présence des genus bactériens - Verveur et Barnenez", x = "genus", y = "Conditions") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5))
print(heatmap_plot_genus)
```

```{r, change l'ordre d'apparition des genres}
# Définir l'ordre désiré pour les genres
order_genus <- c("Pseudomonas", "Pseudoalteromonas", "Cobetia", "Vibrio", "Algoriphagus", "Flavobacterium", "Pseudalkalibacillus", "Shewanella", "Bacillus", "Paraglaciecola", "Salinibacterium", "Winogradskyella", "Rahnella", "Cellulophaga", "Pseudovibrio", "Rheinheimera", "Zobellia", "Microbacterium", "Aliiglaciecola", "Carnobacterium", "Cellvibrio", "Cytobacillus", "Demequina", "Formosa", "Hydrogenophaga", "Marinagarivorans", "Metabacillus", "Motilimonas", "Niallia", "Nonlabens", "Olleya", "Paracoccus", "Pedobacter", "Peribacillus", "Plantibacter", "Polaribacter", "Pseudocolwellia", "Pseudorhodobacter", "Pseudosulfitobacter", "Psychromonas", "Sanguibacter", "Stenotrophomonas", "Tenacibaculum", "Yoonia")

# Convertir la variable genus en un facteur avec l'ordre spécifié
heatmap_data_genus$genus <- factor(heatmap_data_genus$genus, levels = order_genus)

# heatmap
heatmap_plot_genus_ordered <- ggplot(heatmap_data_genus, aes(x = genus, y = Condition, fill = count)) +
  geom_tile() +
  geom_text(aes(label = count), vjust = 0.5, color = "white") +  
  scale_fill_gradient(low = "skyblue", high = "darkblue") +
  labs(title = "Heatmap de présence des genres bactériens - Verveur et Barnenez", x = "Genus", y = "Conditions") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5))

print(heatmap_plot_genus_ordered)

```

```{r, plot combine heatmap barplot }
# Compter le nombre d'occurrences de chaque genus pour chaque échantillon
genus_counts_BarnenezGDND <- table(filtered_data_BarnenezGDND$genus)
genus_counts_BarnenezGDDEP <- table(filtered_data_BarnenezGDDEP$genus)
genus_counts_BarnenezEau <- table(filtered_data_BarnenezEau$genus)
genus_counts_BarnenezSedi <- table(filtered_data_BarnenezSedi$genus)

genus_counts_VerveurGDND <- table(filtered_data_VerveurGDND$genus)
genus_counts_VerveurGDDEP <- table(filtered_data_VerveurGDDEP$genus)
genus_counts_VerveurEau <- table(filtered_data_VerveurEau$genus)
genus_counts_VerveurSedi <- table(filtered_data_VerveurSedi$genus)

# Créer une dataframe pour chaque échantillon
heatmap_datagenus_BarnenezGDND <- data.frame(genus = names(genus_counts_BarnenezGDND), count = as.numeric(genus_counts_BarnenezGDND), Condition = "BarnenezGDND")
heatmap_datagenus_BarnenezGDDEP <- data.frame(genus = names(genus_counts_BarnenezGDDEP), count = as.numeric(genus_counts_BarnenezGDDEP), Condition = "BarnenezGDDEP")
heatmap_datagenus_BarnenezEau <- data.frame(genus = names(genus_counts_BarnenezEau), count = as.numeric(genus_counts_BarnenezEau), Condition = "BarnenezEau")
heatmap_datagenus_BarnenezSedi <- data.frame(genus = names(genus_counts_BarnenezSedi), count = as.numeric(genus_counts_BarnenezSedi), Condition = "BarnenezSedi")

heatmap_datagenus_VerveurGDND <- data.frame(genus = names(genus_counts_VerveurGDND), count = as.numeric(genus_counts_VerveurGDND), Condition = "VerveurGDND")
heatmap_datagenus_VerveurGDDEP <- data.frame(genus = names(genus_counts_VerveurGDDEP), count = as.numeric(genus_counts_VerveurGDDEP), Condition = "VerveurGDDEP")
heatmap_datagenus_VerveurEau <- data.frame(genus = names(genus_counts_VerveurEau), count = as.numeric(genus_counts_VerveurEau), Condition = "VerveurEau")
heatmap_datagenus_VerveurSedi <- data.frame(genus = names(genus_counts_VerveurSedi), count = as.numeric(genus_counts_VerveurSedi), Condition = "VerveurSedi")

# Fusionner les dataframes
heatmap_data_genus <- rbind(heatmap_datagenus_BarnenezGDND, heatmap_datagenus_BarnenezGDDEP, heatmap_datagenus_BarnenezEau, heatmap_datagenus_BarnenezSedi, heatmap_datagenus_VerveurGDND, heatmap_datagenus_VerveurGDDEP, heatmap_datagenus_VerveurEau, heatmap_datagenus_VerveurSedi)

# Définir l'ordre désiré pour les conditions
order_conditions <- c("BarnenezGDDEP", "BarnenezGDND", "BarnenezSedi", "BarnenezEau", 
                      "VerveurGDDEP", "VerveurGDND", "VerveurSedi", "VerveurEau")

# Convertir la variable Condition en un facteur avec l'ordre spécifié
heatmap_data_genus$Condition <- factor(heatmap_data_genus$Condition, levels = order_conditions)

# Generate the barplot with the genres sorted in the desired order
bar_plot_combinedgenresclasses <- ggplot(top_genres_combined3, aes(x = reorder(Genus, -Count), y = Count, fill = Ville)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(data = subset(top_genres_combined3, duplicated_genus == FALSE), aes(label = Label), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 7) +
  geom_text(data = subset(top_genres_combined3, duplicated_genus == TRUE), aes(label = symbol, x = Genus, y = symbol_y_pos + 0.9), color = "black", size = 7) +
  labs(title = "Genres retrouvés sur les sites de Verveur et Barnenez", x = NULL, y = "Nombre de souches") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  scale_fill_manual(values = c("Barnenez" = "#145C9E", "Verveur" = "#59C9A5")) +
  scale_y_continuous(labels = scales::comma, breaks = seq(0, 15, 1), limits = c(0, 16)) +
  annotate("text", x = 1, y = 16, size = 3, label = "9.65%", color = "black") +
  annotate("text", x = 2, y = 13, size = 3, label = "12.4%", color = "black") +
  annotate("text", x = 3, y = 10, size = 3, label = "5.5%", color = "black") +
  annotate("text", x = 4, y = 10, size = 3, label = "9%", color = "black") +
  annotate("text", x = 5, y = 8, size = 3, label = "6.2%", color = "black") +
  annotate("text", x = 6, y = 6, size = 3, label = "2.75%", color = "black") +
  annotate("text", x = 7, y = 6, size = 3, label = "5.5%", color = "black") +
  annotate("text", x = 8, y = 7, size = 3, label = "5.5%", color = "black") +
  annotate("text", x = 9, y = 6, size = 3, label = "4.1%", color = "black") +
  annotate("text", x = 10, y = 5, size = 3, label = "4.1%", color = "black") +
  annotate("text", x = 11, y = 5, size = 3, label = "2%", color = "black") +
  annotate("text", x = 12, y = 5, size = 3, label = "2%", color = "black") +
  annotate("text", x = 13, y = 6, size = 3, label = "3.4%", color = "black") +
  annotate("text", x = 14, y = 4, size = 3, label = "2.75%", color = "black") +
  annotate("text", x = 15, y = 4, size = 3, label = "1.4%", color = "black") +
  annotate("text", x = 16, y = 4, size = 3, label = "1.4%", color = "black") +
  annotate("text", x = 17, y = 4, size = 3, label = "1.4%", color = "black") +
  annotate("text", x = 18, y = 4, size = 3, label = "2%", color = "black") +
  #bracket
  annotate("segment", x = 19, xend = 19, y = 2.2, yend = 2.5, size = 0.5, color = "black") + #barre de gauche
  annotate("segment", x = 19, xend = 44, y = 2.5, yend = 2.5, size = 0.5, color = "black") + #barre longueur
  annotate("segment", x = 44, xend = 44, y = 2.2, yend = 2.5, size = 0.5, color = "black") + #barre de droite
  annotate("segment", x = 31, xend = 31, y = 2.5, yend = 2.8, size = 0.5, color = "black") + #petite barre milieu
  annotate("text", x = 31, y = 3.2, size = 3, label = "18.6%", color = "black") + #texte au dessus du bracket
  theme(legend.position = "right", 
        legend.text = element_text(size = 20), 
        axis.title.y = element_text(size = 25), 
        axis.text.y = element_text(size = 15),
        plot.title = element_text(size = 25, hjust = 0.5)) + 
  guides(fill = guide_legend(title = "Sites:", title.theme = element_text(size = 20)))

#Légende symboles pour classes bactérienne 
legend_text <- paste(names(class_symbols), class_symbols, sep = ": ")
legend_text <- paste(legend_text, collapse = "\n")
legend_title <- "Classes bactérienne :"
# Concaténer les textes avec le titre de la légende
legend_text <- paste(legend_title, "\n", legend_text)
bar_plot_combinedgenresclasses <- bar_plot_combinedgenresclasses + 
  annotate("text", x = Inf, y = Inf, label = legend_text, hjust = 1, vjust = 1, size = 5, color = "black", parse = FALSE)

# Définir l'ordre désiré pour les genres
order_genus <- c("Pseudomonas", "Pseudoalteromonas", "Cobetia", "Vibrio", "Algoriphagus", "Flavobacterium", "Pseudalkalibacillus", "Shewanella", "Bacillus", "Paraglaciecola", "Salinibacterium", "Winogradskyella", "Rahnella", "Cellulophaga", "Pseudovibrio", "Rheinheimera", "Zobellia", "Microbacterium", "Aliiglaciecola", "Carnobacterium", "Cellvibrio", "Cytobacillus", "Demequina", "Formosa", "Hydrogenophaga", "Marinagarivorans", "Metabacillus", "Motilimonas", "Niallia", "Nonlabens", "Olleya", "Paracoccus", "Pedobacter", "Peribacillus", "Plantibacter", "Polaribacter", "Pseudocolwellia", "Pseudorhodobacter", "Pseudosulfitobacter", "Psychromonas", "Sanguibacter", "Stenotrophomonas", "Tenacibaculum", "Yoonia")

# Convertir la variable genus en un facteur avec l'ordre spécifié
heatmap_data_genus$genus <- factor(heatmap_data_genus$genus, levels = order_genus)

separation_position_y <- 4.5  # Position entre les conditions

# heatmap
heatmap_plot_genus_ordered <- ggplot(heatmap_data_genus, aes(x = genus, y = Condition, fill = count)) +
  geom_tile() +
  geom_text(aes(label = count), vjust = 0.5, color = "white") +  
  scale_fill_gradient(low = "skyblue", high = "darkblue", name = "Nombre 
de souches :") + # Modifier le titre de la légende
  labs(x = "Genres", y = "Compartiments") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 20), # genres
        axis.text.y = element_text(size = 15), # légende heatmap axe des ordonnées
        plot.title = element_text(hjust = 0.5),
        legend.text = element_text(size = 15), # Modifier la taille du texte de la légende (légende du code couleur)
        legend.title = element_text(size = 20), # Modifier la taille du titre de la légende (nb de séquences)
        axis.title = element_text(size = 25)) + # Modifier la taille du texte des étiquettes des axes x et y
 geom_hline(yintercept = separation_position_y, linetype = "longdash", color = "#EF3E36", size = 1)  

# Combiner les deux graphiques en un seul plot verticalement aligné
combined_plot_heatbarplot <- bar_plot_combinedgenresclasses / heatmap_plot_genus_ordered + plot_layout(ncol = 1, heights = c(1, 2))

combined_plot_heatbarplot <- wrap_plots(bar_plot_combinedgenresclasses, heatmap_plot_genus_ordered, ncol = 1)
print(combined_plot_heatbarplot)

```



```{r, Uniquement pour Barnenez Eau} 
class_counts_BarnenezEau <- table(filtered_data_BarnenezEau$genus)

bar_plot_BarnenezEau <- ggplot(data.frame(Genus = names(class_counts_BarnenezEau), Count = as.numeric(class_counts_BarnenezEau)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#145C9E") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +
  labs(title = "genres retrouvés - Barnenez Eau", x = "class", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  # Ajout de l'annotation pour le nombre total de séquences
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_BarnenezEau)), hjust = 1, vjust = 0)

print(bar_plot_BarnenezEau)
```

```{r, Uniquement pour Verveur Eau} 


class_counts_VerveurEau <- table(filtered_data_VerveurEau$genus)



bar_plot_VerveurEau <- ggplot(data.frame(Genus = names(class_counts_VerveurEau), Count = as.numeric(class_counts_VerveurEau)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#59C9A5") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +
  labs(title = "genres retrouvés - Verveur Eau", x = "class", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  # Ajout de l'annotation pour le nombre total de séquences
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_VerveurEau)), hjust = 1, vjust = 0)

print(bar_plot_VerveurEau)
```

```{r, Uniquement pour Barnenez Sédiments} 
class_counts_BarnenezSedi <- table(filtered_data_BarnenezSedi$genus)

bar_plot_BarnenezSedi <- ggplot(data.frame(Genus = names(class_counts_BarnenezSedi), Count = as.numeric(class_counts_BarnenezSedi)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#145C9E") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +
  labs(title = "genres retrouvés - Barnenez Sédiments", x = "class", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  # Ajout de l'annotation pour le nombre total de séquences
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_BarnenezSedi)), hjust = 1, vjust = 0)
  
print(bar_plot_BarnenezSedi)
```
```{r, Uniquement pour Verveur Sédiments} 
class_counts_VerveurSedi <- table(filtered_data_VerveurSedi$genus)

bar_plot_VerveurSedi <- ggplot(data.frame(Genus = names(class_counts_VerveurSedi), Count = as.numeric(class_counts_VerveurSedi)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#59C9A5") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +
  labs(title = "genres retrouvés - Verveur Sédiments", x = "class", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  # Ajout de l'annotation pour le nombre total de séquences
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_VerveurSedi)), hjust = 1, vjust = 0)
  
print(bar_plot_VerveurSedi)
```

```{r, Uniquement pour Barnenez GDND} 
class_counts_BarnenezGDND <- table(filtered_data_BarnenezGDND$genus)

bar_plot_BarnenezGDND <- ggplot(data.frame(Genus = names(class_counts_BarnenezGDND), Count = as.numeric(class_counts_BarnenezGDND)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#145C9E") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +
  scale_y_continuous(labels = scales::comma, breaks = seq(0, 3, 1), limits = c(0, 3)) +  # Modifier l'échelle des données y
  labs(title = "genres retrouvés - Barnenez GDND", x = "class", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_BarnenezGDND)), hjust = 1, vjust = 0)
  
print(bar_plot_BarnenezGDND)
```

```{r, Uniquement pour Verveur GDND} 
class_counts_VerveurGDND <- table(filtered_data_VerveurGDND$genus)

bar_plot_VerveurGDND <- ggplot(data.frame(Genus = names(class_counts_VerveurGDND), Count = as.numeric(class_counts_VerveurGDND)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#59C9A5") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +
  labs(title = "genres retrouvés - Verveur GDND", x = "class", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_VerveurGDND)), hjust = 1, vjust = 0)
  
print(bar_plot_VerveurGDND)
```

```{r, Uniquement pour Barnenez GDDEP} 
class_counts_BarnenezGDDEP <- table(filtered_data_BarnenezGDDEP$genus)

bar_plot_BarnenezGDDEP <- ggplot(data.frame(Genus = names(class_counts_BarnenezGDDEP), Count = as.numeric(class_counts_BarnenezGDDEP)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#145C9E") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +
  labs(title = "genres retrouvés - Barnenez GDDEP", x = "class", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_BarnenezGDDEP)), hjust = 1, vjust = 0)
  
print(bar_plot_BarnenezGDDEP)
```

```{r, Uniquement pour Verveur GDDEP} 
class_counts_VerveurGDDEP <- table(filtered_data_VerveurGDDEP$genus)

bar_plot_VerveurGDDEP <- ggplot(data.frame(Genus = names(class_counts_VerveurGDDEP), Count = as.numeric(class_counts_VerveurGDDEP)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "#59C9A5") +
  geom_text(aes(label = Count), position = position_dodge(width = 0.9), vjust = -0.5, color = "black", size = 3.5) +
  labs(title = "genres retrouvés - Verveur GDDEP", x = "class", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_VerveurGDDEP)), hjust = 1, vjust = 0)
  
print(bar_plot_VerveurGDDEP)
```

```{r, diagramme de Venn barnenez}
# Extraire les genres uniques de chaque échantillon
genres_BarnenezEau <- unique(data_BarnenezEau$genus)
genres_BarnenezSedi <- unique(data_BarnenezSedi$genus)
genres_BarnenezGDND <- unique(data_BarnenezGDND$genus)
genres_BarnenezGDDEP <- unique(data_BarnenezGDDEP$genus)

# Créer une liste avec les ensembles pour chaque échantillon
sets_listBarnenez <- list(
  BarnenezEau = genres_BarnenezEau,
  BarnenezSedi = genres_BarnenezSedi,
  BarnenezGDND = genres_BarnenezGDND,
  BarnenezGDDEP = genres_BarnenezGDDEP
)

# Créer un diagramme de Venn avec ggvenn
venn_plotBarnenez <- ggvenn(sets_listBarnenez , show_elements = TRUE,
  show_percentage = FALSE,
  digits = 1,
  fill_color = c("skyblue", "orange2", "#1B998B", "#C5D86D"),
  fill_alpha = 1.5,
  stroke_color = "black",
  stroke_alpha = 1,
  stroke_size = 0.1,
  stroke_linetype = "solid",
  set_name_color = "black",
  set_name_size = 6, 
  text_size = 3.5, 
  label_sep = "
  ",
  count_column = NULL,
  show_outside = c("auto", "none", "always")
)

# Récupérer les chiffres pour chaque ensemble
counts <- venn_plotBarnenez$data$label

# Ajouter les étiquettes aux positions appropriées
venn_plotBarnenez +
  annotate("text", x = counts$x, y = counts$y, label = counts$label, color = "black") +
  theme_minimal(base_size = 8) +  # Ajustez la taille de la police du thème global si nécessaire
  theme_void()  # Retire le quadrillage de fond
```

```{r, diagramme de Venn barnenez eaux sedi gdnd}
# Créer une liste avec les ensembles pour chaque échantillon
sets_listBarnenez1 <- list(
  BarnenezEau = genres_BarnenezEau,
  BarnenezSedi = genres_BarnenezSedi,
  BarnenezGDND = genres_BarnenezGDND
)

# Créer un diagramme de Venn avec ggvenn
venn_plotBarnenez1 <- ggvenn(sets_listBarnenez1 , show_elements = TRUE,
  show_percentage = FALSE,
  digits = 1,
  fill_color = c("skyblue", "orange2", "#1B998B"),
  fill_alpha = 1.5,
  stroke_color = "black",
  stroke_alpha = 1,
  stroke_size = 0.1,
  stroke_linetype = "solid",
  set_name_color = "black",
  set_name_size = 5, 
  text_size = 3.5, 
  label_sep = "
  ",
  count_column = FALSE,
  show_outside = c("auto", "none", "always")
)

# Récupérer les chiffres pour chaque ensemble
counts <- venn_plotBarnenez1$data$label

# Ajouter les étiquettes aux positions appropriées
venn_plotBarnenez1 +
  annotate("text", x = counts$x, y = counts$y, label = counts$label, color = "black") +
  theme_minimal(base_size = 8) +  # Ajustez la taille de la police du thème global si nécessaire
  theme_void()  # Retire le quadrillage de fond
```

```{r, diagramme de Venn barnenez gdnd gddep}
sets_listBarnenez2 <- list(
  BarnenezGDND = genres_BarnenezGDND,
  BarnenezGDDEP = genres_BarnenezGDDEP
)

venn_plotBarnenez2 <- ggvenn(sets_listBarnenez2, show_elements = TRUE,
  show_percentage = FALSE,
  digits = 1,
  fill_color = c("#1B998B", "#C5D86D"),
  fill_alpha = 1.5,
  stroke_color = "black",
  stroke_alpha = 1,
  stroke_size = 0.1,
  stroke_linetype = "solid", 
  set_name_color = "black",
  set_name_size = 5,  # Ajustez la taille de la police ici BarnenezSedi BarnenezEau BarnenezGD..
  text_size = 4,  # Ajustez la taille de la police pour les genres
  label_sep = "
  ",
  count_column = NULL,
)

# Récupérer les chiffres pour chaque ensemble
counts <- venn_plotBarnenez2$data$label

# Ajouter les étiquettes aux positions appropriées
venn_plotBarnenez2 +
  annotate("text", x = counts$x, y = counts$y, label = counts$label, color = "black") +
  theme_minimal(base_size = 8) +  # Ajustez la taille de la police du thème global si nécessaire
  theme_void()  # Retire le quadrillage de fond
```

```{r, liaison diag venn}
grid.arrange(venn_plotBarnenez1, venn_plotBarnenez2, ncol = 2)
```



```{r, venn complet Verveur}
# Extraire les genres uniques de chaque échantillon
genres_VerveurEau <- unique(data_VerveurEau$genus)
genres_VerveurSedi <- unique(data_VerveurSedi$genus)
genres_VerveurGDND <- unique(data_VerveurGDND$genus)
genres_VerveurGDDEP <- unique(data_VerveurGDDEP$genus)

# Créer une liste avec les ensembles pour chaque échantillon
sets_listVerveur <- list(
  VerveurEau = genres_VerveurEau,
  VerveurSedi = genres_VerveurSedi,
  VerveurGDND = genres_VerveurGDND,
  VerveurGDDEP = genres_VerveurGDDEP
)

# Créer un diagramme de Venn avec ggvenn
venn_plotVerveur <- ggvenn(sets_listVerveur , show_elements = TRUE,
  show_percentage = FALSE,
  digits = 1,
  fill_color = c("skyblue", "orange2", "#1B998B", "#C5D86D"),
  fill_alpha = 1.5,
  stroke_color = "black",
  stroke_alpha = 1,
  stroke_size = 0.1,
  stroke_linetype = "solid",
  set_name_color = "black",
  set_name_size = 5,  # Ajustez la taille de la police ici VerveurSedi VerveurEau VerveurGD..
  text_size = 3.5,  # Ajustez la taille de la police pour les genres
  label_sep = "
  ",
  count_column = NULL,
  show_outside = c("auto", "none", "always")
)

# Récupérer les chiffres pour chaque ensemble
counts <- venn_plotVerveur$data$label

# Ajouter les étiquettes aux positions appropriées
venn_plotVerveur +
  annotate("text", x = counts$x, y = counts$y, label = counts$label, color = "black") +
  theme_minimal(base_size = 8) +  # Ajustez la taille de la police du thème global si nécessaire
  theme_void()  # Retire le quadrillage de fond
```

```{r, venn verveur sedi eau gdnd}
# Créer une liste avec les ensembles pour chaque échantillon
sets_listVerveur1 <- list(
  VerveurEau = genres_VerveurEau,
  VerveurSedi = genres_VerveurSedi,
  VerveurGDND = genres_VerveurGDND
)

# Créer un diagramme de Venn avec ggvenn
venn_plotVerveur1 <- ggvenn(sets_listVerveur1 , show_elements = TRUE,
  show_percentage = FALSE,
  digits = 1,
  fill_color = c("skyblue", "orange2", "#1B998B"),
  fill_alpha = 1.5,
  stroke_color = "black",
  stroke_alpha = 1,
  stroke_size = 0.1,
  stroke_linetype = "solid",
  set_name_color = "black",
  set_name_size = 6,  # Ajustez la taille de la police ici VerveurSedi VerveurEau VerveurGD..
  text_size = 3.5,  # Ajustez la taille de la police pour les genres
  label_sep = "
  ",
  count_column = NULL,
  show_outside = c("auto", "none", "always")
)

# Récupérer les chiffres pour chaque ensemble
counts <- venn_plotVerveur1$data$label

# Ajouter les étiquettes aux positions appropriées
venn_plotVerveur1 +
  annotate("text", x = counts$x, y = counts$y, label = counts$label, color = "black") +
  theme_minimal(base_size = 8) +  # Ajustez la taille de la police du thème global si nécessaire
  theme_void()  # Retire le quadrillage de fond
```

```{r, venn verveur gdnd gddep}

# Créer une liste avec les ensembles pour chaque échantillon
sets_listVerveur2 <- list(
  VerveurGDND = genres_VerveurGDND,
  VerveurGDDEP = genres_VerveurGDDEP
)

# Créer un diagramme de Venn avec ggvenn
venn_plotVerveur2 <- ggvenn(sets_listVerveur2 , show_elements = TRUE,
  show_percentage = FALSE,
  digits = 1,
  fill_color = c("#1B998B", "#C5D86D"),
  fill_alpha = 1.5,
  stroke_color = "black",
  stroke_alpha = 1,
  stroke_size = 0.1,
  stroke_linetype = "solid",
  set_name_color = "black",
  set_name_size = 5,  # Ajustez la taille de la police ici VerveurSedi VerveurEau VerveurGD..
  text_size = 4,  # Ajustez la taille de la police pour les genres
  label_sep = "
  ",
  count_column = NULL,
  show_outside = c("auto", "none", "always")
)

# Récupérer les chiffres pour chaque ensemble
counts <- venn_plotVerveur2$data$label

# Ajouter les étiquettes aux positions appropriées
venn_plotVerveur2 +
  annotate("text", x = counts$x, y = counts$y, label = counts$label, color = "black") +
  theme_minimal(base_size = 8) +  # Ajustez la taille de la police du thème global si nécessaire
  theme_void()  # Retire le quadrillage de fond
```

```{r, pdf save}
pdf("Figures/Figures.pdf", width = 12, height = 8)

grid.arrange(heatmap_plot_genus)

grid.arrange(heatmap_plot_class)

grid.arrange(bar_plot_combined3)

grid.arrange(combined_plot_heatbarplot)

grid.arrange(venn_plotVerveur1, venn_plotVerveur2,
             ncol = 2)

grid.arrange(venn_plotBarnenez1, venn_plotBarnenez2,
             ncol = 2)

dev.off()
```

```{r, sauvegarde des figures indiv}
ggsave("Figures/FiguresCommun/bar_plot_combined.png", bar_plot_combined, width = 10, height = 6, units = "in")
ggsave("Figures/FiguresCommun/bar_plot_combined2.png", bar_plot_combined2, width = 10, height = 6, units = "in")
ggsave("Figures/FiguresCommun/bar_plot_combined3.png", bar_plot_combined3, width = 10, height = 6, units = "in")
ggsave("Figures/FiguresCommun/heatmap_plot_class.png", heatmap_plot_class, width = 10, height = 6, units = "in")
ggsave("Figures/FiguresCommun/heatmap_plot_genus.png", heatmap_plot_genus, width = 10, height = 6, units = "in")
ggsave("Figures/FiguresCommun/combined_plot_heatbarplot.png", combined_plot_heatbarplot, width = 10, height = 6, units = "in")

ggsave("Figures/FiguresBarnenez/bar_plot_BarnenezEau.png", bar_plot_BarnenezEau, width = 6, height = 4, units = "in")
ggsave("Figures/FiguresBarnenez/bar_plot_BarnenezSedi.png", bar_plot_BarnenezSedi, width = 6, height = 4, units = "in")
ggsave("Figures/FiguresBarnenez/bar_plot_BarnenezGDND.png", bar_plot_BarnenezGDND, width = 6, height = 4, units = "in")
ggsave("Figures/FiguresBarnenez/bar_plot_BarnenezGDDEP.png", bar_plot_BarnenezGDDEP)
ggsave("Figures/FiguresBarnenez/venn_plotBarnenez.png", venn_plotBarnenez)
ggsave("Figures/FiguresBarnenez/bar_plotBarnenezTot.png", bar_plotBarnenezTot, width = 6, height = 6, units = "in")
ggsave("Figures/FiguresBarnenez/venn_plotBarnenez1.png", venn_plotBarnenez1)
ggsave("Figures/FiguresBarnenez/venn_plotBarnenez2.png", venn_plotBarnenez2)

ggsave("Figures/FiguresVerveur/bar_plot_VerveurEau.png", bar_plot_BarnenezEau, width = 6, height = 4, units = "in")
ggsave("Figures/FiguresVerveur/bar_plot_VerveurSedi.png", bar_plot_BarnenezSedi, width = 6, height = 4, units = "in")
ggsave("Figures/FiguresVerveur/bar_plot_VerveurGDND.png", bar_plot_BarnenezGDND, width = 6, height = 4, units = "in")
ggsave("Figures/FiguresVerveur/bar_plot_VerveurGDDEP.png", bar_plot_BarnenezGDDEP, width = 6, height = 4, units = "in")
ggsave("Figures/FiguresVerveur/venn_plotVerveur.png", venn_plotVerveur)
ggsave("Figures/FiguresVerveur/venn_plotVerveur1.png", venn_plotVerveur1)
ggsave("Figures/FiguresVerveur/venn_plotVerveur2.png", venn_plotVerveur2)
```


