---
title: "R Notebook"
output: html_notebook
---


#Installer Blast+ https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/
#Télécharger database 16s de NCBI https://ftp.ncbi.nlm.nih.gov/blast/db/ (16S_ribosomal_RNA...)

```{r, eval=FALSE, packages mais il doit en manquer, voir avec les library}
install.packages(c("VennDiagram", "VennCounts"))
install.packages("readxl")

```

```{r library, include=FALSE}
library(readxl)
library(openxlsx)
library(VennDiagram)
library(DECIPHER)
library(openxlsx)
library(rmarkdown)
library(knitr)
library(phyloseq)
library(dada2)
library(DECIPHER)
library(phangorn)
library(ggplot2)
library(gridExtra)
library(shiny)
library(miniUI)
library(caret)
library(pls)
library(e1071)
library(ggplot2)
library(randomForest)
library(dplyr)
library(ggrepel)
#library(nlme)
library(devtools)
library(reshape2)
library(PMA)
#library(structSSI)
library(ade4)
library(ggnetwork)
library(intergraph)
library(scales)
library(genefilter)
library(impute)
library(phyloseqGraphTest)
library(Biostrings)
library(RSQLite)
library(parallel)
library(ape)
library(taxonomizr)
library('rBLAST')
```

```{r, eval=FALSE, créer la data base, prévoire 2-3 et 80go de stockage, NE LANCER qu'une fois}
libdir='data'
dir.create(libdir)
setwd(libdir)
getNamesAndNodes()
getAccession2taxid(types=c('nucl_gb'))
getAccession2taxid()
system("gunzip *.gz")
read.accession2taxid(list.files('.','accession2taxid'),'accessionTaxa.sql')
print(paste('taxonomizr database built and located at', getwd(), sep=' '))
```

```{r, Ne lancer que si la commande suivante ne fonctionne pas en spécifiant le path de blast+}
Sys.setenv(PATH = paste(Sys.getenv("PATH"), "C:/Program Files/NCBI/blast-2.15.0+/bin", sep= .Platform$path.sep))
```

```{r}
#BLAST query
file_list_MorlaixEau <- list.files('/Users/amrozins/Documents/workflow/FASTAtest/MorlaixEau', pattern = "\\.fa$", full.names = TRUE)
file_list_MorlaixSedi <- list.files('/Users/amrozins/Documents/workflow/FASTAtest/MorlaixSedi', pattern = "\\.fa$", full.names = TRUE)
file_list_MorlaixGDND <- list.files('/Users/amrozins/Documents/workflow/FASTAtest/MorlaixGDND', pattern = "\\.fa$", full.names = TRUE)
file_list_MorlaixGDDEP <- list.files('/Users/amrozins/Documents/workflow/FASTAtest/MorlaixGDDEP', pattern = "\\.fa$", full.names = TRUE)

dna_MorlaixEau <- readDNAStringSet(file_list_MorlaixEau, format='fasta')
dna_MorlaixSedi <- readDNAStringSet(file_list_MorlaixSedi, format='fasta')
dna_MorlaixGDND <- readDNAStringSet(file_list_MorlaixGDND, format='fasta')
dna_MorlaixGDDEP <- readDNAStringSet(file_list_MorlaixGDDEP, format='fasta')

bl <- blast(db="/Users/amrozins/Documents/workflow/16S_ribosomal_RNA/16S_ribosomal_RNA")

#Run BLAST query

cl_MorlaixEau <- predict(bl, dna_MorlaixEau)
cl_MorlaixSedi <- predict(bl, dna_MorlaixSedi)
cl_MorlaixGDND <- predict(bl, dna_MorlaixGDND)
cl_MorlaixGDDEP <- predict(bl, dna_MorlaixGDDEP)

cl_MorlaixEau[1:5,]
#to view first 5 hits
summary(cl_MorlaixEau)

cl_MorlaixSedi[1:5,]
summary(cl_MorlaixSedi)

cl_MorlaixGDND[1:5,]
summary(cl_MorlaixGDND)

cl_MorlaixGDDEP[1:5,]
summary(cl_MorlaixGDDEP)
```

```{r}
accid_MorlaixEau = as.character(cl_MorlaixEau$sseqid)
accid_MorlaixSedi = as.character(cl_MorlaixSedi$sseqid)
accid_MorlaixGDND = as.character(cl_MorlaixGDND$sseqid)
accid_MorlaixGDDEP = as.character(cl_MorlaixGDDEP$sseqid)
```

```{r}
taxaNodes<-read.nodes.sql("/Users/amrozins/Documents/workflow/data/nodes.dmp")
taxaNames<-read.names.sql("/Users/amrozins/Documents/workflow/data/names.dmp")
```

```{r}
#takes accession number and gets the taxonomic ID
ids_MorlaixEau<-accessionToTaxa(accid_MorlaixEau, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
#taxlist displays the taxonomic names from each ID #
taxlist_MorlaixEau=getTaxonomy(ids_MorlaixEau, taxaNodes, taxaNames)


ids_MorlaixSedi<-accessionToTaxa(accid_MorlaixSedi, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_MorlaixSedi=getTaxonomy(ids_MorlaixSedi, taxaNodes, taxaNames)

ids_MorlaixGDND<-accessionToTaxa(accid_MorlaixGDND, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_MorlaixGDND=getTaxonomy(ids_MorlaixGDND, taxaNodes, taxaNames)

ids_MorlaixGDDEP<-accessionToTaxa(accid_MorlaixGDDEP, '/Users/amrozins/Documents/workflow/data/accessionTaxa.sql')
taxlist_MorlaixGDDEP=getTaxonomy(ids_MorlaixGDDEP, taxaNodes, taxaNames)
```

```{r}
#Résultats Totaux MorlaixEau
cltax_MorlaixEau=cbind(cl_MorlaixEau,taxlist_MorlaixEau) #bind BLAST hits and taxonomy table
colnames(cltax_MorlaixEau)
cltax_MorlaixEau
```

```{r}
#Résultats Totaux MorlaixSedi
cltax_MorlaixSedi=cbind(cl_MorlaixSedi,taxlist_MorlaixSedi) #bind BLAST hits and taxonomy table
colnames(cltax_MorlaixSedi)
cltax_MorlaixSedi
```

```{r}
#Résultats Totaux MorlaixGDND
cltax_MorlaixGDND=cbind(cl_MorlaixGDND,taxlist_MorlaixGDND) 
colnames(cltax_MorlaixGDND)
cltax_MorlaixGDND
```

```{r}
#Résultats Totaux MorlaixGDDEP
cltax_MorlaixGDDEP=cbind(cl_MorlaixGDDEP,taxlist_MorlaixGDDEP)
colnames(cltax_MorlaixGDDEP)
cltax_MorlaixGDDEP
```

```{r}
# Tri des résultats par qseqid et pident décroissants
cltax_sorted_MorlaixEau <- cltax_MorlaixEau %>% arrange(qseqid, desc(pident))

# Sélection des 5 premiers résultats pour chaque qseqid
cltax5_MorlaixEau <- cltax_sorted_MorlaixEau %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_MorlaixEau)
```

```{r}
cltax_sorted_MorlaixSedi <- cltax_MorlaixSedi %>% arrange(qseqid, desc(pident))
cltax5_MorlaixSedi <- cltax_sorted_MorlaixSedi %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_MorlaixSedi)
```

```{r}
cltax_sorted_MorlaixGDND <- cltax_MorlaixGDND %>% arrange(qseqid, desc(pident))
cltax5_MorlaixGDND <- cltax_sorted_MorlaixGDND %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_MorlaixGDND)
```

```{r}
cltax_sorted_MorlaixGDDEP <- cltax_MorlaixGDDEP %>% arrange(qseqid, desc(pident))
cltax5_MorlaixGDDEP <- cltax_sorted_MorlaixGDDEP %>% group_by(qseqid) %>% slice_head(n = 5)
print(cltax5_MorlaixGDDEP)
```

```{r}
#Ne prend pour chaque fasta que le résultat avec le max de % identity (pident)
filtered_cltax_MorlaixEau <- cltax_sorted_MorlaixEau %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))

filtered_cltax_MorlaixEau
```

```{r}
filtered_cltax_MorlaixSedi <- cltax_sorted_MorlaixSedi %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_MorlaixSedi
```

```{r}
filtered_cltax_MorlaixGDND <- cltax_sorted_MorlaixGDND %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_MorlaixGDND
```

```{r}
filtered_cltax_MorlaixGDDEP <- cltax_sorted_MorlaixGDDEP %>%
  group_by(qseqid) %>%
  filter(pident == max(pident))
filtered_cltax_MorlaixGDDEP
```

#Pour sortir les TabRésultats

```{r}
#Pour sortir uniquement les résultats de taxo
data_MorlaixEau <- subset(filtered_cltax_MorlaixEau, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident))

print(data_MorlaixEau)
```

```{r}
#Résultats de taxo et ajoutes la longueur de la séquence et la séquence
data_MorlaixEau <- subset(filtered_cltax_MorlaixEau, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident))

# Emplacement des fichiers .fasta
chemin_du_dossier_MorlaixEau <- "/Users/amrozins/Documents/workflow/FASTA/MorlaixEau"

# Fonction pour lire le contenu d'un fichier FASTA avec correspondance partielle
lire_fasta_MorlaixEau <- function(qseqid, chemin_du_dossier_MorlaixEau) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_MorlaixEau <- list.files(chemin_du_dossier_MorlaixEau, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_MorlaixEau) > 0) {
        seqs_MorlaixEau <- readDNAStringSet(fichiers_MorlaixEau[1], format = "fasta")
        return(as.character(seqs_MorlaixEau))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

# Ajouter une colonne au DataFrame avec le contenu des fichiers FASTA
data_MorlaixEau$sequence <- sapply(data_MorlaixEau$qseqid, lire_fasta_MorlaixEau, chemin_du_dossier_MorlaixEau)

# Ajouter une colonne avec la longueur des séquences dans contenu_fasta
data_MorlaixEau$longueur_sequence_pb <- sapply(data_MorlaixEau$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_MorlaixEau <- data_MorlaixEau[, c(names(data_MorlaixEau)[names(data_MorlaixEau) != "sequence"], "sequence")]

# Afficher le DataFrame mis à jour
print(data_MorlaixEau)
```




```{r}
data_MorlaixSedi <- subset(filtered_cltax_MorlaixSedi, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident))
chemin_du_dossier_MorlaixSedi <- "/Users/amrozins/Documents/workflow/FASTA/MorlaixSedi"

lire_fasta_MorlaixSedi <- function(qseqid, chemin_du_dossier_MorlaixSedi) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_MorlaixSedi <- list.files(chemin_du_dossier_MorlaixSedi, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_MorlaixSedi) > 0) {
        seqs_MorlaixSedi <- readDNAStringSet(fichiers_MorlaixSedi[1], format = "fasta")
        return(as.character(seqs_MorlaixSedi))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_MorlaixSedi$sequence <- sapply(data_MorlaixSedi$qseqid, lire_fasta_MorlaixSedi, chemin_du_dossier_MorlaixSedi)
data_MorlaixSedi$longueur_sequence_pb <- sapply(data_MorlaixSedi$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_MorlaixSedi <- data_MorlaixSedi[, c(names(data_MorlaixSedi)[names(data_MorlaixSedi) != "sequence"], "sequence")]
print(data_MorlaixSedi)
```


```{r}
data_MorlaixGDND <- subset(filtered_cltax_MorlaixGDND, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident))
chemin_du_dossier_MorlaixGDND <- "/Users/amrozins/Documents/workflow/FASTA/MorlaixGDND"

lire_fasta_MorlaixGDND <- function(qseqid, chemin_du_dossier_MorlaixGDND) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_MorlaixGDND <- list.files(chemin_du_dossier_MorlaixGDND, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_MorlaixGDND) > 0) {
        seqs_MorlaixGDND <- readDNAStringSet(fichiers_MorlaixGD[1], format = "fasta")
        return(as.character(seqs_MorlaixGDND))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_MorlaixGDND$sequence <- sapply(data_MorlaixGDND$qseqid, lire_fasta_MorlaixGDND, chemin_du_dossier_MorlaixGDND)
data_MorlaixGDND$longueur_sequence_pb <- sapply(data_MorlaixGDND$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_MorlaixGDND <- data_MorlaixGDND[, c(names(data_MorlaixGDND)[names(data_MorlaixGDND) != "sequence"], "sequence")]
print(data_MorlaixGDND)
```

```{r}
data_MorlaixGDDEP <- subset(filtered_cltax_MorlaixGDDEP, 
                  select=c(qseqid, superkingdom, phylum, class, order, family, genus, species, pident))
chemin_du_dossier_MorlaixGDDEP <- "/Users/amrozins/Documents/workflow/FASTA/MorlaixGDDEP"

lire_fasta_MorlaixGDDEP <- function(qseqid, chemin_du_dossier_MorlaixGDDEP) {
    pattern <- paste0("^", gsub("\\.ab1$", "", qseqid), ".*\\.fa$")
    fichiers_MorlaixGDDEP <- list.files(chemin_du_dossier_MorlaixGDDEP, pattern = pattern, full.names = TRUE, ignore.case = TRUE)
    
    if (length(fichiers_MorlaixGDDEP) > 0) {
        seqs_MorlaixGDDEP <- readDNAStringSet(fichiers_MorlaixGDDEP[1], format = "fasta")
        return(as.character(seqs_MorlaixGDDEP))
    } else {
        cat("Aucun fichier correspondant trouvé pour :", qseqid, "\n")
        return(NA)
    }
}

data_MorlaixGDDEP$sequence <- sapply(data_MorlaixGDDEP$qseqid, lire_fasta_MorlaixGDDEP, chemin_du_dossier_MorlaixGDDEP)
data_MorlaixGDDEP$longueur_sequence_pb <- sapply(data_MorlaixGDDEP$sequence, function(seq) ifelse(is.na(seq), NA, nchar(seq)))
data_MorlaixGDDEP <- data_MorlaixGDDEP[, c(names(data_MorlaixGDDEP)[names(data_MorlaixGDDEP) != "sequence"], "sequence")]
print(data_MorlaixGDDEP)
```

```{r}
# Sauvegarder data_MorlaixGDND au format CSV
write.csv(data_MorlaixGDND, "/Users/amrozins/Documents/workflow/Résultats/data_MorlaixGDND.csv", row.names = FALSE)
```

```{r}
# Sauvegarder data_MorlaixGDDEP au format CSV
write.csv(data_MorlaixGDDEP, "/Users/amrozins/Documents/workflow/Résultats/data_MorlaixGDDEP.csv", row.names = FALSE)
```

```{r}
# Sauvegarder data_MorlaixSedi au format CSV
write.csv(data_MorlaixSedi, "/Users/amrozins/Documents/workflow/Résultats/data_MorlaixSedi.csv", row.names = FALSE)
```

```{r}
# Sauvegarder data_MorlaixEau au format CSV
write.csv(data_MorlaixEau, "/Users/amrozins/Documents/workflow/Résultats/data_MorlaixEau.csv", row.names = FALSE)
```

```{r}
#Combine les .csv

# Chemin du fichier Excel de sortie
output_excel_path <- "/Users/amrozins/Documents/workflow/Résultats/combined_dataMorlaix.xlsx"

# Écrire les données dans un fichier Excel avec plusieurs feuilles
write.xlsx(list(data_MorlaixGDND = data_MorlaixGDND, 
                data_MorlaixGDDEP = data_MorlaixGDDEP,
                data_MorlaixSedi = data_MorlaixSedi, 
                data_MorlaixEau = data_MorlaixEau),
           file = output_excel_path)
```

#Représentations Graphique

```{r, Représentation graphique des genres les plus retrouvés pour Morlaix Eau / Sédiments / GD}
# Filtrer pour ne conserver que le résultat avec le plus grand pident par fichier .fa
filtered_data_MorlaixEau <- data_MorlaixEau[order(-data_MorlaixEau$pident), ]
filtered_data_MorlaixEau <- filtered_data_MorlaixEau[!duplicated(filtered_data_MorlaixEau$qseqid), ]

filtered_data_MorlaixSedi <- data_MorlaixSedi[order(-data_MorlaixSedi$pident), ]
filtered_data_MorlaixSedi <- filtered_data_MorlaixSedi[!duplicated(filtered_data_MorlaixSedi$qseqid), ]

filtered_data_MorlaixGDND <- data_MorlaixGDND[order(-data_MorlaixGDND$pident), ]
filtered_data_MorlaixGDND <- filtered_data_MorlaixGDND[!duplicated(filtered_data_MorlaixGDND$qseqid), ]

filtered_data_MorlaixGDDEP <- data_MorlaixGDDEP[order(-data_MorlaixGDDEP$pident), ]
filtered_data_MorlaixGDDEP <- filtered_data_MorlaixGDDEP[!duplicated(filtered_data_MorlaixGDDEP$qseqid), ]

# Combinez les données filtrées en une seule dataframe
all_filtered_data <- rbind(filtered_data_MorlaixEau, filtered_data_MorlaixSedi, filtered_data_MorlaixGDND, filtered_data_MorlaixGDDEP)

# Tableau de comptage des genres
genre_counts <- table(all_filtered_data$genus)

# Sélectionnez les 10 genres les plus retrouvés
top_genres <- head(sort(genre_counts, decreasing = TRUE), 10)

# Créez le graphique à barres
bar_plot <- ggplot(data.frame(Genus = names(top_genres), Count = as.numeric(top_genres)), 
                   aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Top 10 Genres les plus retrouvés pour Morlaix : Eau / Sédiments / GD (DEP et ND)", x = "Genre", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(all_filtered_data)), hjust = 1, vjust = 0)

print(bar_plot)
```


```{r, Uniquement pour Morlaix Eau} 
filtered_data_MorlaixEau <- data_MorlaixEau[order(-data_MorlaixEau$pident), ]
filtered_data_MorlaixEau <- filtered_data_MorlaixEau[!duplicated(filtered_data_MorlaixEau$qseqid), ]

genre_counts_MorlaixEau <- table(filtered_data_MorlaixEau$genus)

top_genres_MorlaixEau <- head(sort(genre_counts_MorlaixEau, decreasing = TRUE), 10)

bar_plot_MorlaixEau <- ggplot(data.frame(Genus = names(top_genres_MorlaixEau), Count = as.numeric(top_genres_MorlaixEau)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Top 10 Genres les plus retrouvés - Morlaix Eau", x = "Genre", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  # Ajout de l'annotation pour le nombre total de séquences
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_MorlaixEau)), hjust = 1, vjust = 0)

print(bar_plot_MorlaixEau)
```

```{r, Uniquement pour Morlaix Sédiments} 
filtered_data_MorlaixSedi <- data_MorlaixSedi[order(-data_MorlaixSedi$pident), ]
filtered_data_MorlaixSedi <- filtered_data_MorlaixSedi[!duplicated(filtered_data_MorlaixSedi$qseqid), ]

genre_counts_MorlaixSedi <- table(filtered_data_MorlaixSedi$genus)

top_genres_MorlaixSedi <- head(sort(genre_counts_MorlaixSedi, decreasing = TRUE), 10)

bar_plot_MorlaixSedi <- ggplot(data.frame(Genus = names(top_genres_MorlaixSedi), Count = as.numeric(top_genres_MorlaixSedi)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Top 10 Genres les plus retrouvés - Morlaix Sédiments", x = "Genre", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  # Ajout de l'annotation pour le nombre total de séquences
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_MorlaixSedi)), hjust = 1, vjust = 0)
  
print(bar_plot_MorlaixSedi)
```

```{r, Uniquement pour Morlaix GDND} 
filtered_data_MorlaixGDND <- data_MorlaixGDND[order(-data_MorlaixGDND$pident), ]
filtered_data_MorlaixGDND <- filtered_data_MorlaixGDND[!duplicated(filtered_data_MorlaixGDND$qseqid), ]

genre_counts_MorlaixGDND <- table(filtered_data_MorlaixGDND$genus)

top_genres_MorlaixGDND <- head(sort(genre_counts_MorlaixGDND, decreasing = TRUE), 10)

bar_plot_MorlaixGDND <- ggplot(data.frame(Genus = names(top_genres_MorlaixGDND), Count = as.numeric(top_genres_MorlaixGDND)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Top 10 Genres les plus retrouvés - Morlaix GDND", x = "Genre", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_MorlaixGDND)), hjust = 1, vjust = 0)
  
print(bar_plot_MorlaixGDND)
```

```{r, Uniquement pour Morlaix GDDEP} 
filtered_data_MorlaixGDDEP <- data_MorlaixGDDEP[order(-data_MorlaixGDDEP$pident), ]
filtered_data_MorlaixGDDEP <- filtered_data_MorlaixGDDEP[!duplicated(filtered_data_MorlaixGDDEP$qseqid), ]

genre_counts_MorlaixGDDEP <- table(filtered_data_MorlaixGDDEP$genus)

top_genres_MorlaixGDDEP <- head(sort(genre_counts_MorlaixGDDEP, decreasing = TRUE), 10)

bar_plot_MorlaixGDDEP <- ggplot(data.frame(Genus = names(top_genres_MorlaixGDDEP), Count = as.numeric(top_genres_MorlaixGDDEP)), 
                              aes(x = reorder(Genus, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Top 10 Genres les plus retrouvés - Morlaix GDDEP", x = "Genre", y = "Nombre de séquences") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  annotate("text", x = Inf, y = -Inf, label = paste("Total de séquences :", nrow(filtered_data_MorlaixGDDEP)), hjust = 1, vjust = 0)
  
print(bar_plot_MorlaixGDDEP)
```

```{r}
# Extraire les genres uniques de chaque échantillon
genres_MorlaixEau <- unique(data_MorlaixEau$genus)
genres_MorlaixSedi <- unique(data_MorlaixSedi$genus)
genres_MorlaixGDND <- unique(data_MorlaixGDND$genus)
genres_MorlaixGDDEP <- unique(data_MorlaixGDDEP$genus)

# Créer une liste avec les ensembles pour chaque échantillon
sets_list <- list(
  MorlaixEau = genres_MorlaixEau,
  MorlaixSedi = genres_MorlaixSedi,
  MorlaixGDND = genres_MorlaixGDND,
  MorlaixGDDEP = genres_MorlaixGDDEP
)

# Créer un diagramme de Venn avec ggvenn
venn_plot <- ggvenn(sets_list, show_elements = TRUE,
  show_percentage = FALSE,
  digits = 1,
  fill_color = c("skyblue", "yellow", "green", "red"),
  fill_alpha = 1.5,
  stroke_color = "black",
  stroke_alpha = 1,
  stroke_size = 1,
  stroke_linetype = "solid",
  set_name_color = "black",
  set_name_size = 3,  # Ajustez la taille de la police ici MorlaixSedi MorlaixEau MorlaixGD..
  text_size = 2,  # Ajustez la taille de la police pour les genres
  label_sep = "
  ",
  count_column = NULL,
  show_outside = c("auto", "none", "always")
)

# Récupérer les chiffres pour chaque ensemble
counts <- venn_plot$data$label

# Ajouter les étiquettes aux positions appropriées
venn_plot +
  annotate("text", x = counts$x, y = counts$y, label = counts$label, color = "black") +
  theme_minimal(base_size = 8) +  # Ajustez la taille de la police du thème global si nécessaire
  theme_void()  # Retire le quadrillage de fond
```

```{r, sauvegarde des figures}
dir.create("FiguresMorlaix", showWarnings = FALSE)

# Enregistrez le graphique global
ggsave("FiguresMorlaix/bar_plot.png", bar_plot, width = 10, height = 6, units = "in")

# Enregistrez les graphiques individuels
ggsave("FiguresMorlaix/bar_plot_MorlaixEau.png", bar_plot_MorlaixEau, width = 6, height = 4, units = "in")
ggsave("FiguresMorlaix/bar_plot_MorlaixSedi.png", bar_plot_MorlaixSedi, width = 6, height = 4, units = "in")
ggsave("FiguresMorlaix/bar_plot_MorlaixGDND.png", bar_plot_MorlaixGDND, width = 6, height = 4, units = "in")
ggsave("FiguresMorlaix/bar_plot_MorlaixGDDEP.png", bar_plot_MorlaixGDDEP, width = 6, height = 4, units = "in")

# Enregistrez le diagramme de Venn
ggsave("FiguresMorlaix/venn_plot.png", venn_plot, width = 6, height = 6, units = "in")
```


